In [1]:
import torch
import numpy

# list, numpy, tensor相互转化

In [ ]:
"""
                             tensor
                         ↗          ↘↖
torch.as_tensor(list1) ↗              ↘↖torch.as_tensor(arr1)
torch.Tensor(list1)  ↗                  ↘↖torch.from_numpy(arr1)
torch.tensor(list1)↗       tensor1.numpy()↘↖torch.Tensor(arr1) 
                 ↗                          ↘↖torch.tensor(arr1)
               ↗       array1.tolist()        ↘↖
            list      <-----------------        numpy
                      ----------------->
                      numpy.array(list1)
"""

## numpy <-> tensor
> Tensors on the CPU and NumPy arrays can share their underlying memory location, and **changing one will change the other**

In [3]:
arr_1 = numpy.array([1,1,1])

arr2tensor_1 = torch.from_numpy(arr_1)    # 共享内存
arr2tensor_2 = torch.as_tensor(arr_1)     # 共享内存
arr2tensor_3 = torch.tensor(arr_1)        # 深拷贝
arr2tensor_4 = torch.Tensor(arr_1)        # 深拷贝
tensor2arr_1 = arr2tensor_1.numpy()      # 共享内存

print('Before modify:', arr2tensor_1)
print('Before modify:', arr2tensor_2)
print('Before modify:', arr2tensor_3)
print('Before modify:', arr2tensor_4)
print('Before modify:', tensor2arr_1)

arr_1 += 1

print('After modify:', arr2tensor_1)
print('After modify:', arr2tensor_2)
print('After modify:', arr2tensor_3)
print('After modify:', arr2tensor_4)
print('After modify:', tensor2arr_1)

Before modify: tensor([1, 1, 1])
Before modify: tensor([1, 1, 1])
Before modify: tensor([1, 1, 1])
Before modify: tensor([1., 1., 1.])
Before modify: [1 1 1]
After modify: tensor([2, 2, 2])
After modify: tensor([2, 2, 2])
After modify: tensor([1, 1, 1])
After modify: tensor([1., 1., 1.])
After modify: [2 2 2]


## list -> tensor

In [4]:
list_1 = [1,1,1]

list2tensor_1 = torch.as_tensor(list_1)   # 深拷贝, 保留原数据类型
list2tensor_2 = torch.tensor(list_1)      # 深拷贝, 保留原数据类型
list2tensor_3 = torch.Tensor(list_1)      # 深拷贝, 保存为float

print('Before modify:', list2tensor_1, list2tensor_1.dtype)
print('Before modify:', list2tensor_2, list2tensor_2.dtype)
print('Before modify:', list2tensor_3, list2tensor_3.dtype)

list_1[1] += 1

print('After modify:', list2tensor_1, list2tensor_1.dtype)
print('After modify:', list2tensor_2, list2tensor_2.dtype)
print('After modify:', list2tensor_3, list2tensor_3.dtype)

Before modify: tensor([1, 1, 1]) torch.int64
Before modify: tensor([1, 1, 1]) torch.int64
Before modify: tensor([1., 1., 1.]) torch.float32
After modify: tensor([1, 1, 1]) torch.int64
After modify: tensor([1, 1, 1]) torch.int64
After modify: tensor([1., 1., 1.]) torch.float32


## torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False)
Data type                | dtype                         | Legacy Constructors
:- | :- | :-
32-bit floating point    | torch.float32 or torch.float  | torch.*.FloatTensor
64-bit floating point    | torch.float64 or torch.double | torch.*.DoubleTensor
64-bit complex           | torch.complex64 or torch.cfloat
128-bit complex          | torch.complex128 or torch.cdouble
16-bit floating point 1  | torch.float16 or torch.half   | torch.*.HalfTensor
16-bit floating point 2  | torch.bfloat16                | torch.*.BFloat16Tensor
8-bit integer (unsigned) | torch.uint8                   | torch.*.ByteTensor
8-bit integer (signed)   | torch.int8                    | torch.*.CharTensor
16-bit integer (signed)  | torch.int16 or torch.short    | torch.*.ShortTensor
32-bit integer (signed)  | torch.int32 or torch.int      | torch.*.IntTensor
64-bit integer (signed)  | torch.int64 or torch.long     | torch.*.LongTensor
Boolean                  | torch.bool                    | torch.*.BoolTensor

In [16]:
tensor_1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float)
print(tensor_1)
print( type(tensor_1) )
print("is a tensor?", torch.is_tensor(tensor_1) )
print( tensor_1.dtype )
print( tensor_1.device )

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
<class 'torch.Tensor'>
is a tensor? True
torch.float32
cpu


In [18]:
print(torch.tensor([1], dtype = torch.complex64),
      "\t\t\t is complex?", torch.is_complex(torch.tensor([1], dtype = torch.complex64)))
print(torch.tensor([1], dtype = torch.complex128),
      "is complex?", torch.is_complex(torch.tensor([1], dtype = torch.complex128)))
print(torch.tensor([1], dtype = torch.float32),
      "\t\t\t\t is float?", torch.is_floating_point(torch.tensor([1], dtype = torch.float32)))
print(torch.tensor([1], dtype = torch.float64),
      "\t is float?", torch.is_floating_point(torch.tensor([1], dtype = torch.float64)))
print(torch.tensor([1], dtype = torch.float16),
      "\t is float?", torch.is_floating_point(torch.tensor([1], dtype = torch.float16)))
print(torch.tensor([1], dtype = torch.bfloat16),
      "\t is float?", torch.is_floating_point(torch.tensor([1], dtype = torch.bfloat16)))

tensor([1.+0.j]) 			 is complex? True
tensor([1.+0.j], dtype=torch.complex128) is complex? True
tensor([1.]) 				 is float? True
tensor([1.], dtype=torch.float64) 	 is float? True
tensor([1.], dtype=torch.float16) 	 is float? True
tensor([1.], dtype=torch.bfloat16) 	 is float? True


# 生成操作
refer to: https://pytorch.org/docs/stable/torch.html

In [23]:
tensor_1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float)

## basic

### torch.zeros
torch.zeros(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [46]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [47]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### torch.zeros_like
torch.zeros_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)

In [29]:
torch.zeros_like(tensor_1)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### torch.ones
torch.ones(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [52]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [53]:
torch.ones((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### torch.ones_like
torch.ones_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)

In [54]:
torch.ones_like(tensor_1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### torch.empty
torch.empty(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False, memory_format=torch.contiguous_format)   
生成一个空的tensor(每个元素为随机的极其小的正值)

In [48]:
torch.empty(2, 3)

tensor([[0.0000e+00, 6.7262e-44, 2.1532e+23],
        [8.3895e-07, 2.1006e+20, 8.1804e+20]])

### torch.empty_like
torch.empty_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)

In [49]:
torch.empty_like(tensor_1)

tensor([[-1.8746e-33,  3.0852e-41, -1.8087e-33],
        [ 3.0852e-41,  1.5695e-43,  0.0000e+00],
        [ 6.7262e-44,  0.0000e+00, -4.6463e-35]])

### torch.full
torch.full(size, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)  
Creates a tensor of size size filled with fill_value

In [41]:
torch.full(size=(2, 3), fill_value=3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

### torch.full_like
torch.full_like(input, fill_value, *, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format)

In [40]:
torch.full_like(tensor_1, fill_value=3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

### torch.eye
torch.eye(n, m=None, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)  
对角线为1

In [50]:
torch.eye(4, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])

In [51]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## sequence

### torch.arange
torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [42]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [43]:
torch.arange(1, 4)

tensor([1, 2, 3])

In [44]:
torch.arange(1, 2.5, 0.5)

tensor([1.0000, 1.5000, 2.0000])

In [55]:
torch.arange(0, 10, 1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### torch.linspace
torch.linspace(start, end, steps, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [56]:
torch.linspace(start=0, end=10, steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [57]:
torch.linspace(-10, 10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

### torch.logspace
torch.logspace(start, end, steps, base=10.0, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [58]:
torch.logspace(start=0, end=10, steps=11)

tensor([1.0000e+00, 1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05,
        1.0000e+06, 1.0000e+07, 1.0000e+08, 1.0000e+09, 1.0000e+10])

In [59]:
torch.logspace(start=0, end=10, steps=11, base=2)

tensor([1.0000e+00, 2.0000e+00, 4.0000e+00, 8.0000e+00, 1.6000e+01, 3.2000e+01,
        6.4000e+01, 1.2800e+02, 2.5600e+02, 5.1200e+02, 1.0240e+03])

### torch.randperm
torch.randperm(n, *, generator=None, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False, pin_memory=False)  
[0, n)之间的一个随机排列

In [62]:
torch.randperm(4)

tensor([0, 2, 3, 1])

## 均分分布

### torch.rand
torch.rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False)  
[0,1)之间的随机小数

In [63]:
torch.rand(2, 3)

tensor([[0.1798, 0.9774, 0.7949],
        [0.0543, 0.1901, 0.9474]])

### torch.rand_like
torch.rand_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)  
[0,1)之间的随机小数

In [64]:
torch.rand_like(tensor_1)

tensor([[0.7106, 0.6199, 0.9579],
        [0.6220, 0.0433, 0.1052],
        [0.4421, 0.5232, 0.3296]])

### torch.randint
torch.randint(low=0, high, size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)  
[low, high)之间的随机整数

In [65]:
torch.randint(low=5, high=10, size=(2, 2))

tensor([[6, 8],
        [8, 5]])

In [66]:
torch.randint(high=10, size=(2,2))

tensor([[9, 1],
        [0, 7]])

### torch.randint_like
torch.randint_like(input, low=0, high, *, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format)  
[low, high)之间的随机整数

In [69]:
torch.randint_like(tensor_1, low=5, high=10)

tensor([[8., 6., 7.],
        [9., 7., 8.],
        [5., 5., 8.]])

In [70]:
torch.randint_like(tensor_1, high=10)

tensor([[3., 9., 6.],
        [7., 5., 9.],
        [2., 6., 0.]])

## 正态分布

### torch.randn
torch.randn(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False)  
标准正态分布, 均值为0, 方差为1

In [71]:
torch.randn(2, 3)

tensor([[-0.3794,  0.6806,  1.0308],
        [-0.1291, -0.7029,  0.2652]])

### torch.randn_like
torch.randn_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)  
标准正态分布, 均值为0, 方差为1

In [72]:
torch.rand_like(tensor_1)

tensor([[0.2268, 0.8732, 0.1223],
        [0.0723, 0.3805, 0.8357],
        [0.1125, 0.5685, 0.6508]])

### torch.normal
torch.normal(mean, std, size, \*, out=None)  
mean is float, std is float  

Parameters:
- mean (float) – the mean for all distributions
- std (float) – the standard deviation for all distributions
- size (int...) – a sequence of integers defining the shape of the output tensor.

In [77]:
torch.normal(mean=2, std=3, size=(1, 5))

tensor([[ 3.1106,  0.8640,  6.8128, -1.1986,  8.0743]])

torch.normal(mean=0.0, std, *, out=None)  
mean is float, std is tensor

Parameters:
- mean (float, optional) – the mean for all distributions
- std (Tensor) – the tensor of per-element standard deviations

In [76]:
torch.normal(mean=0.5, std=torch.arange(1., 6.))

tensor([1.6693, 2.9867, 3.4782, 3.2756, 7.3793])

torch.normal(mean, std=1.0, *, out=None)  
mean is tensor, std is float  

Parameters:  
- mean (Tensor) – the tensor of per-element means
- std (float, optional) – the standard deviation for all distributions

In [79]:
torch.normal(mean=torch.arange(1., 6.))

tensor([1.9557, 2.6027, 1.4790, 3.5888, 6.8464])

torch.normal(mean, std, *, generator=None, out=None)  
mean is tensor, std is tensor  

Parameters:
- mean (Tensor) – the tensor of per-element means
- std (Tensor) – the tensor of per-element standard deviations

In [83]:
torch.normal(mean=torch.arange(1., 6.), std=torch.arange(1, 0, -0.2))

tensor([-0.3819,  2.2231,  4.2730,  4.5564,  5.4564])

## 多项式分布

### torch.multinomial
torch.multinomial(input, num_samples, replacement=False, \*, generator=None, out=None)
基于多项式分布，从input中随机抽取num_samples元素，并返回其索引
- input的每行之和无需一定为1, 但必须是大于0的有限数
- replacement=False 表示无重复抽取, 0 < num_samples <= len(input[0])
- replacement=True 表示可重复抽取, num_samples > 0

In [84]:
torch.multinomial(torch.tensor([[0., 10., 3.],[4., 2., 8.]]), 2)

tensor([[2, 1],
        [2, 1]])

In [85]:
torch.multinomial(torch.tensor([[0., 10., 3.],[4., 2., 8.]]), 3)

tensor([[1, 2, 0],
        [2, 0, 1]])

In [87]:
torch.multinomial(torch.tensor([[0., 10., 3.],[4., 2., 8.]]), 4, replacement=True)

tensor([[1, 1, 1, 1],
        [0, 2, 0, 2]])

## 0-1分布

### torch.bernoulli
torch.bernoulli(input, *, generator=None, out=None)  
input的每个元素都必须在[0,1]内

In [90]:
torch.bernoulli(torch.rand(2, 3))

tensor([[0., 1., 0.],
        [1., 1., 1.]])

## 泊松分布

### torch.poisson
torch.poisson(input, generator=None)

In [92]:
torch.poisson(torch.rand(2, 3) * 5)

tensor([[1., 3., 1.],
        [7., 3., 6.]])

# Indexing, Slicing, Joining, Mutating Ops

## 形状

In [115]:
tensor_1 = torch.tensor([[1,2,3,4],[5,6,7,8]], dtype=torch.float)

print(tensor_1)

print("total number of elements =", tensor_1.numel() )
print("total number of elements =", torch.numel(tensor_1) )

print("size:", tensor_1.shape)
print("size:", tensor_1.size())

print("total number of dimensions =", tensor_1.dim() )

print("size of 0-th dim =", tensor_1.shape[0] )
print("size of 0-th dim =", tensor_1.size(0) )
print("size of 0-th dim =", tensor_1.size()[0] )

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
total number of elements = 8
total number of elements = 8
size: torch.Size([2, 4])
size: torch.Size([2, 4])
total number of dimensions = 2
size of 0-th dim = 2
size of 0-th dim = 2
size of 0-th dim = 2


## 查找/索引
不会开辟新内存

In [117]:
print("first element:", tensor_1[0][0].item() )
print("first element:", tensor_1[0,0].item() )
print("first row:",     tensor_1[0] )
print("Last column:",   tensor_1[:,-1] )
print("Last column:",   tensor_1[...,-1] )

first element: 1.0
first element: 1.0
first row: tensor([1., 2., 3., 4.])
Last column: tensor([4., 8.])
Last column: tensor([4., 8.])


>Notice: 索引返回的结果与原数据共享内存，也即修改一个，另一个会跟着修改

In [119]:
tensor_1[:,1] = 0
tensor_1

tensor([[1., 0., 3., 4.],
        [5., 0., 7., 8.]])

### torch.take
torch.take(input, index)

In [120]:
torch.take(tensor_1, torch.tensor([0,2,5,7]))

tensor([1., 3., 0., 8.])

### torch.take_along_dim
torch.take_along_dim(input, indices, dim, \*, out=None)  
input and indices should have the same number of dimensions

In [159]:
tensor_1 = torch.tensor([[4,2,3,1],[5,7,6,8]], dtype=torch.float)

In [160]:
tensor_1

tensor([[4., 2., 3., 1.],
        [5., 7., 6., 8.]])

In [161]:
sorted_idx = torch.argsort(tensor_1, dim=1)

In [162]:
sorted_idx

tensor([[3, 1, 2, 0],
        [0, 2, 1, 3]])

In [163]:
torch.take_along_dim(tensor_1, sorted_idx, dim=1)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

### torch.masked_select
torch.masked_select(input, mask, \*, out=None)  
Returns a new 1-D tensor which indexes the input tensor according to the boolean mask mask which is a BoolTensor.  
返回mask为真的元素组成的一维张量

In [164]:
tensor_1 = torch.tensor([[4,2,3,1],[5,7,6,8]], dtype=torch.float)

In [165]:
tensor_1

tensor([[4., 2., 3., 1.],
        [5., 7., 6., 8.]])

In [166]:
mask = torch.tensor([[True,False,True,False],[False,True,False,True]])

In [167]:
torch.masked_select(tensor_1, mask)

tensor([4., 3., 7., 8.])

### torch.nonzero
torch.nonzero(input, *, out=None, as_tuple=False)  
非0位置索引

In [169]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]))

tensor([[0],
        [1],
        [2],
        [4]])

In [171]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]), as_tuple=False)

tensor([[0],
        [1],
        [2],
        [4]])

In [172]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]), as_tuple=True)

(tensor([0, 1, 2, 4]),)

In [173]:
torch.nonzero(torch.tensor([[0.6, 0.0],[0.0, 0.4],[0.0, 0.0],[0.0, -0.4]]))

tensor([[0, 0],
        [1, 1],
        [3, 1]])

In [174]:
torch.nonzero(torch.tensor([[0.6, 0.0],[0.0, 0.4],[0.0, 0.0],[0.0, -0.4]]), as_tuple=True)

(tensor([0, 1, 3]), tensor([0, 1, 1]))

### torch.where
torch.where(condition, input, other, *, out=None)  
$$ out_i = \begin{cases} \begin{array}{l,l}
input_i, & condition_i = True \\
other_i, & otherwise \\
\end{array} \end{cases} $$

Parameters:
- condition (BoolTensor) – When True (nonzero), yield input, otherwise yield other
- input (Tensor or Scalar) – value (if input is a scalar) or values selected at indices where condition is True
- other (Tensor or Scalar) – value (if other is a scalar) or values selected at indices where condition is False

In [178]:
tensor_1 = torch.tensor([[-0.462, 0.3139],[0.3898, -0.7197]], dtype=torch.float64)
tensor_2 = torch.zeros_like(tensor_1)

In [180]:
tensor_1

tensor([[-0.4620,  0.3139],
        [ 0.3898, -0.7197]], dtype=torch.float64)

In [179]:
torch.where(tensor_1 > 0, 1.0, 0.0)

tensor([[0., 1.],
        [1., 0.]])

In [182]:
torch.where(tensor_1 > 0, tensor_1, 1.0)

tensor([[1.0000, 0.3139],
        [0.3898, 1.0000]], dtype=torch.float64)

In [183]:
torch.where(tensor_1 > 0, tensor_1, tensor_2)

tensor([[0.0000, 0.3139],
        [0.3898, 0.0000]], dtype=torch.float64)

## 变形

### torch.reshape
torch.reshape(input, shape)  
$\iff$ tensor_1.view(shape)

In [212]:
tensor_1 = torch.arange(1, 25)

In [185]:
tensor_1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

In [187]:
torch.reshape(tensor_1, (2, 3, 4))

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [188]:
tensor_1.view(2, 3, 4)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [189]:
torch.reshape(tensor_1, (8, -1)) # -1 表示24/8

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]])

In [190]:
tensor_1.view(8, -1)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]])

In [192]:
torch.reshape(tensor_1, (-1, 4)) # -1 表示24/4

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])

In [194]:
tensor_1.view(-1, 4)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])

In [196]:
torch.reshape(tensor_1,(2, -1, 4)) # -1 表示24/2/4

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [197]:
tensor_1.view(2, -1, 4)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [198]:
torch.reshape(tensor_1, (24,)) #一行

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

In [199]:
tensor_1.view(24,)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

In [200]:
torch.reshape(tensor_1, (-1,)) #一行

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

In [201]:
tensor_1.view(-1,)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

>变形虽然生成新的tensor，但是与源Tensor共享数据<br>即改变一个变形中的数值，所有tensor的数值一起发生变化

In [217]:
tensor_1 = torch.arange(1, 25)
print(tensor_1, ", id =", id(tensor_1))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24]) , id = 139938644464160


In [218]:
tensor_2 = torch.reshape(tensor_1, (2, 3, 4))
print(tensor_2, ", id =", id(tensor_2))

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]) , id = 139938644413472


In [219]:
tensor_3 = tensor_1.view(4, 6) 
print(tensor_3, ", id =", id(tensor_3))

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]) , id = 139938632112864


In [220]:
tensor_2 -= 12
print(tensor_1)
print(tensor_2)
print(tensor_3)

tensor([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12])
tensor([[[-11, -10,  -9,  -8],
         [ -7,  -6,  -5,  -4],
         [ -3,  -2,  -1,   0]],

        [[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]]])
tensor([[-11, -10,  -9,  -8,  -7,  -6],
        [ -5,  -4,  -3,  -2,  -1,   0],
        [  1,   2,   3,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12]])


>如果不想修改源tensor，需要将源tensor深拷贝后再进行变形<br>即深拷贝后再修改变形的数值，则不会影响源tensor数值

In [226]:
print(tensor_1, ", id =", id(tensor_1))

tensor([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12]) , id = 139938644464160


In [227]:
tensor_4 = tensor_1.clone().view(3, 8)
print(tensor_4, ", id =", id(tensor_4))

tensor([[-11, -10,  -9,  -8,  -7,  -6,  -5,  -4],
        [ -3,  -2,  -1,   0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9,  10,  11,  12]]) , id = 139938644479008


In [228]:
tensor_4 += 12
print(tensor_1)
print(tensor_4)

tensor([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])


### torch.clone
torch.clone(input, *, memory_format=torch.preserve_format)  
This function is differentiable, so gradients will flow back from the result of this operation to input.

In [229]:
print(tensor_1, id(tensor_1))
tensor_2 = torch.clone(tensor_1)
print(tensor_2, id(tensor_2))

tensor([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12]) 139938644464160
tensor([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12]) 139938656457168


## 降维

### torch.squeeze
torch.squeeze(input, dim=None)

In [232]:
tensor_1 = torch.zeros(2, 1, 3, 1, 2)

In [233]:
tensor_1.size()

torch.Size([2, 1, 3, 1, 2])

In [234]:
torch.squeeze(tensor_1).size()

torch.Size([2, 3, 2])

In [235]:
torch.squeeze(tensor_1, dim=0).size()

torch.Size([2, 1, 3, 1, 2])

In [236]:
torch.squeeze(tensor_1, dim=1).size()

torch.Size([2, 3, 1, 2])

### torch.unsqueeze
torch.unsqueeze(input, dim)   
A dim value within the range $[-input.dim() - 1, input.dim() + 1)$ can be used. Negative dim will correspond to unsqueeze() applied at dim = dim + input.dim() + 1.

In [242]:
for index in range(-tensor_1.dim()-1, tensor_1.dim()+1):
    print("dim =",index, ":", torch.unsqueeze(tensor_1, dim=index).size() )

dim = -6 : torch.Size([1, 2, 1, 3, 1, 2])
dim = -5 : torch.Size([2, 1, 1, 3, 1, 2])
dim = -4 : torch.Size([2, 1, 1, 3, 1, 2])
dim = -3 : torch.Size([2, 1, 3, 1, 1, 2])
dim = -2 : torch.Size([2, 1, 3, 1, 1, 2])
dim = -1 : torch.Size([2, 1, 3, 1, 2, 1])
dim = 0 : torch.Size([1, 2, 1, 3, 1, 2])
dim = 1 : torch.Size([2, 1, 1, 3, 1, 2])
dim = 2 : torch.Size([2, 1, 1, 3, 1, 2])
dim = 3 : torch.Size([2, 1, 3, 1, 1, 2])
dim = 4 : torch.Size([2, 1, 3, 1, 1, 2])
dim = 5 : torch.Size([2, 1, 3, 1, 2, 1])


### torch.movedim
torch.movedim(input, source, destination)
### torch.moveaxis
torch.moveaxis(input, source, destination)  
move source-th dim to destination-th dim

In [243]:
tensor_1 = torch.zeros(2, 1, 3, 1, 2)
tensor_1.size()

torch.Size([2, 1, 3, 1, 2])

In [244]:
torch.movedim(tensor_1, 1, 0).size()

torch.Size([1, 2, 3, 1, 2])

In [245]:
torch.moveaxis(tensor_1, 1, 0).size()

torch.Size([1, 2, 3, 1, 2])

In [246]:
torch.movedim(tensor_1, (1, 2), (0, 1)).size()

torch.Size([1, 3, 2, 1, 2])

In [247]:
torch.moveaxis(tensor_1, (1, 2), (0, 1)).size()

torch.Size([1, 3, 2, 1, 2])

### torch.unbind
torch.unbind(input, dim=0)

In [250]:
tensor_1 = torch.tensor([[1,2,3],[4,5,6]])

In [251]:
torch.unbind(tensor_1, dim=0)

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [252]:
torch.unbind(tensor_1, dim=1)

(tensor([1, 4]), tensor([2, 5]), tensor([3, 6]))

## 转置

### torch.transpose
torch.transpose(input, dim0, dim1)
### torch.swapaxes
torch.swapaxes(input, dim0, dim1)
### torch.swapdims
torch.swapdims(input, dim0, dim1)  
dim0 与 dim1 维度交换

In [264]:
tensor_1 = torch.arange(1, 121).reshape(2, 3, 4, 5)

In [265]:
torch.transpose(tensor_1, dim0=0, dim1=1).size()

torch.Size([3, 2, 4, 5])

In [270]:
torch.swapaxes(tensor_1, axis0=0, axis1=1).size()

torch.Size([3, 2, 4, 5])

In [271]:
torch.swapdims(tensor_1, dim0=0, dim1=1).size()

torch.Size([3, 2, 4, 5])

In [266]:
torch.transpose(tensor_1, dim0=0, dim1=2).size()

torch.Size([4, 3, 2, 5])

In [267]:
torch.transpose(tensor_1, dim0=1, dim1=2).size()

torch.Size([2, 4, 3, 5])

### torch.t
torch.t(input)  
1. 0-D and 1-D tensors are returned as is. 
2. When input is a 2-D tensor this is equivalent to transpose(input, 0, 1).

In [272]:
torch.t(torch.tensor([1,2,3]))

tensor([1, 2, 3])

In [273]:
torch.t(torch.tensor([[1,2,3],[4,5,6]]))

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [274]:
torch.transpose(torch.tensor([[1,2,3],[4,5,6]]), 0, 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

## 拼接

In [ ]:
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2 = torch.tensor([[7,8,9],[10,11,12]])

print( torch.cat((tensor1, tensor2), dim=1) )
print( '<=>', torch.hstack((tensor1,tensor2)) ) # 水平拼接，二位或多维张量沿着dim=1拼接，一维张量沿着dim=0拼接
print( '<=>', torch.column_stack((tensor1,tensor2)) ) # 二位或多维张量沿着dim=1拼接，一维张量转置再沿着dim=1拼接

print( torch.cat((tensor1, tensor2), dim=0) )
print( '<=>', torch.vstack((tensor1,tensor2)) ) # 垂直拼接
print( '<=>', torch.row_stack((tensor1,tensor2)) ) # 同上

print( torch.stack((tensor1, tensor2), dim=0) ) #沿新维度拼接矩阵，新维度是dim=0
print( torch.stack((tensor1, tensor2), dim=1) ) #沿新维度拼接矩阵，新维度是dim=1

print( torch.stack((tensor1, tensor2), dim=2) ) #与下行命令效果一样
print( '<=>', torch.dstack((tensor1,tensor2)) ) #沿第三轴拼接