refer to: https://pytorch.org/docs/stable/torch.html  
《动手学深度学习》 http://tangshusen.me/Dive-into-DL-PyTorch/#/  

In [2]:
import torch
import numpy

# list, numpy, tensor相互转化

In [ ]:
"""
                             tensor
                         ↗          ↘↖
torch.as_tensor(list1) ↗              ↘↖torch.as_tensor(arr1)
torch.Tensor(list1)  ↗                  ↘↖torch.from_numpy(arr1)
torch.tensor(list1)↗       tensor1.numpy()↘↖torch.Tensor(arr1) 
                 ↗                          ↘↖torch.tensor(arr1)
               ↗       array1.tolist()        ↘↖
            list      <-----------------        numpy
                      ----------------->
                      numpy.array(list1)
"""

## numpy <-> tensor
> Tensors on the CPU and NumPy arrays can share their underlying memory location, and **changing one will change the other**

In [3]:
arr_1 = numpy.array([1,1,1])

arr2tensor_1 = torch.from_numpy(arr_1)    # 共享内存
arr2tensor_2 = torch.as_tensor(arr_1)     # 共享内存
arr2tensor_3 = torch.tensor(arr_1)        # 深拷贝
arr2tensor_4 = torch.Tensor(arr_1)        # 深拷贝
tensor2arr_1 = arr2tensor_1.numpy()      # 共享内存

print('Before modify:', arr2tensor_1)
print('Before modify:', arr2tensor_2)
print('Before modify:', arr2tensor_3)
print('Before modify:', arr2tensor_4)
print('Before modify:', tensor2arr_1)

arr_1 += 1

print('After modify:', arr2tensor_1)
print('After modify:', arr2tensor_2)
print('After modify:', arr2tensor_3)
print('After modify:', arr2tensor_4)
print('After modify:', tensor2arr_1)

Before modify: tensor([1, 1, 1])
Before modify: tensor([1, 1, 1])
Before modify: tensor([1, 1, 1])
Before modify: tensor([1., 1., 1.])
Before modify: [1 1 1]
After modify: tensor([2, 2, 2])
After modify: tensor([2, 2, 2])
After modify: tensor([1, 1, 1])
After modify: tensor([1., 1., 1.])
After modify: [2 2 2]


## list -> tensor

In [4]:
list_1 = [1,1,1]

list2tensor_1 = torch.as_tensor(list_1)   # 深拷贝, 保留原数据类型
list2tensor_2 = torch.tensor(list_1)      # 深拷贝, 保留原数据类型
list2tensor_3 = torch.Tensor(list_1)      # 深拷贝, 保存为float

print('Before modify:', list2tensor_1, list2tensor_1.dtype)
print('Before modify:', list2tensor_2, list2tensor_2.dtype)
print('Before modify:', list2tensor_3, list2tensor_3.dtype)

list_1[1] += 1

print('After modify:', list2tensor_1, list2tensor_1.dtype)
print('After modify:', list2tensor_2, list2tensor_2.dtype)
print('After modify:', list2tensor_3, list2tensor_3.dtype)

Before modify: tensor([1, 1, 1]) torch.int64
Before modify: tensor([1, 1, 1]) torch.int64
Before modify: tensor([1., 1., 1.]) torch.float32
After modify: tensor([1, 1, 1]) torch.int64
After modify: tensor([1, 1, 1]) torch.int64
After modify: tensor([1., 1., 1.]) torch.float32


## torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False)
Data type                | dtype                         | Legacy Constructors
:- | :- | :-
32-bit floating point    | torch.float32 or torch.float  | torch.*.FloatTensor
64-bit floating point    | torch.float64 or torch.double | torch.*.DoubleTensor
64-bit complex           | torch.complex64 or torch.cfloat
128-bit complex          | torch.complex128 or torch.cdouble
16-bit floating point 1  | torch.float16 or torch.half   | torch.*.HalfTensor
16-bit floating point 2  | torch.bfloat16                | torch.*.BFloat16Tensor
8-bit integer (unsigned) | torch.uint8                   | torch.*.ByteTensor
8-bit integer (signed)   | torch.int8                    | torch.*.CharTensor
16-bit integer (signed)  | torch.int16 or torch.short    | torch.*.ShortTensor
32-bit integer (signed)  | torch.int32 or torch.int      | torch.*.IntTensor
64-bit integer (signed)  | torch.int64 or torch.long     | torch.*.LongTensor
Boolean                  | torch.bool                    | torch.*.BoolTensor

In [16]:
tensor_1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float)
print(tensor_1)
print( type(tensor_1) )
print("is a tensor?", torch.is_tensor(tensor_1) )
print( tensor_1.dtype )
print( tensor_1.device )

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
<class 'torch.Tensor'>
is a tensor? True
torch.float32
cpu


In [18]:
print(torch.tensor([1], dtype = torch.complex64),
      "\t\t\t is complex?", torch.is_complex(torch.tensor([1], dtype = torch.complex64)))
print(torch.tensor([1], dtype = torch.complex128),
      "is complex?", torch.is_complex(torch.tensor([1], dtype = torch.complex128)))
print(torch.tensor([1], dtype = torch.float32),
      "\t\t\t\t is float?", torch.is_floating_point(torch.tensor([1], dtype = torch.float32)))
print(torch.tensor([1], dtype = torch.float64),
      "\t is float?", torch.is_floating_point(torch.tensor([1], dtype = torch.float64)))
print(torch.tensor([1], dtype = torch.float16),
      "\t is float?", torch.is_floating_point(torch.tensor([1], dtype = torch.float16)))
print(torch.tensor([1], dtype = torch.bfloat16),
      "\t is float?", torch.is_floating_point(torch.tensor([1], dtype = torch.bfloat16)))

tensor([1.+0.j]) 			 is complex? True
tensor([1.+0.j], dtype=torch.complex128) is complex? True
tensor([1.]) 				 is float? True
tensor([1.], dtype=torch.float64) 	 is float? True
tensor([1.], dtype=torch.float16) 	 is float? True
tensor([1.], dtype=torch.bfloat16) 	 is float? True


# 生成操作

In [23]:
tensor_1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float)

## basic

### torch.zeros
torch.zeros(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [46]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [50]:
torch.equal(torch.zeros(2, 3),
            torch.zeros((2,3)))

True

### torch.zeros_like
torch.zeros_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)

In [29]:
torch.zeros_like(tensor_1)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### torch.ones
torch.ones(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [52]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [51]:
torch.equal(torch.ones(2, 3),
            torch.ones((2,3)))

True

### torch.ones_like
torch.ones_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)

In [54]:
torch.ones_like(tensor_1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### torch.empty
torch.empty(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False, memory_format=torch.contiguous_format)   
生成一个空的tensor(每个元素为随机的极其小的正值)

In [48]:
torch.empty(2, 3)

tensor([[0.0000e+00, 6.7262e-44, 2.1532e+23],
        [8.3895e-07, 2.1006e+20, 8.1804e+20]])

### torch.empty_like
torch.empty_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)

In [49]:
torch.empty_like(tensor_1)

tensor([[-1.8746e-33,  3.0852e-41, -1.8087e-33],
        [ 3.0852e-41,  1.5695e-43,  0.0000e+00],
        [ 6.7262e-44,  0.0000e+00, -4.6463e-35]])

### torch.full
torch.full(size, fill_value, \*, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)  
**用fill_value填充tensor的每个元素**

In [41]:
torch.full(size=(2, 3), fill_value=3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

### torch.full_like
torch.full_like(input, fill_value, *, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format)

In [40]:
torch.full_like(tensor_1, fill_value=3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

### torch.eye
torch.eye(n, m=None, \*, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)  
**对角线元素均为1的矩阵**

In [50]:
torch.eye(4, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])

In [51]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## sequence
todo: https://pytorch.org/docs/stable/generated/torch.logspace.html#torch.logspace

### torch.arange
torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [52]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [53]:
torch.arange(1, 6)

tensor([1, 2, 3, 4, 5])

In [54]:
torch.arange(1., 2.5, 0.5)

tensor([1.0000, 1.5000, 2.0000])

In [55]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

### torch.linspace
torch.linspace(start, end, steps, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [56]:
torch.linspace(start=0, end=10, steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [57]:
torch.linspace(-10, 10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

### torch.logspace
torch.logspace(start, end, steps, base=10.0, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

In [58]:
torch.logspace(start=0, end=10, steps=11)

tensor([1.0000e+00, 1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05,
        1.0000e+06, 1.0000e+07, 1.0000e+08, 1.0000e+09, 1.0000e+10])

In [59]:
torch.logspace(start=0, end=10, steps=11, base=2)

tensor([1.0000e+00, 2.0000e+00, 4.0000e+00, 8.0000e+00, 1.6000e+01, 3.2000e+01,
        6.4000e+01, 1.2800e+02, 2.5600e+02, 5.1200e+02, 1.0240e+03])

### torch.randperm 随机排列
torch.randperm(n, \*, generator=None, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False, pin_memory=False)  
**[0, n)之间的一个随机排列**

In [62]:
torch.randperm(4)

tensor([0, 2, 3, 1])

## 均分分布

### torch.rand 随机整数
torch.rand(\*size, \*, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False)  
**[0,1)之间的随机小数**

In [63]:
torch.rand(2, 3)

tensor([[0.1798, 0.9774, 0.7949],
        [0.0543, 0.1901, 0.9474]])

### torch.rand_like
torch.rand_like(input, \*, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)  
**[0,1)之间的随机小数**

In [64]:
torch.rand_like(tensor_1)

tensor([[0.7106, 0.6199, 0.9579],
        [0.6220, 0.0433, 0.1052],
        [0.4421, 0.5232, 0.3296]])

### torch.randint 随机整数
torch.randint(low=0, high, size, \*, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)  
**[low, high)之间的随机整数**

In [65]:
torch.randint(low=5, high=10, size=(2, 2))

tensor([[6, 8],
        [8, 5]])

In [66]:
torch.randint(high=10, size=(2,2))

tensor([[9, 1],
        [0, 7]])

### torch.randint_like
torch.randint_like(input, low=0, high, \*, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format)  
**[low, high)之间的随机整数**

In [69]:
torch.randint_like(tensor_1, low=5, high=10)

tensor([[8., 6., 7.],
        [9., 7., 8.],
        [5., 5., 8.]])

In [70]:
torch.randint_like(tensor_1, high=10)

tensor([[3., 9., 6.],
        [7., 5., 9.],
        [2., 6., 0.]])

## 正态分布

### torch.randn
torch.randn(\*size, \*, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False)  
**标准正态分布, 均值为0, 方差为1**

In [71]:
torch.randn(2, 3)

tensor([[-0.3794,  0.6806,  1.0308],
        [-0.1291, -0.7029,  0.2652]])

### torch.randn_like
torch.randn_like(input, \*, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)  
**标准正态分布, 均值为0, 方差为1**

In [72]:
torch.rand_like(tensor_1)

tensor([[0.2268, 0.8732, 0.1223],
        [0.0723, 0.3805, 0.8357],
        [0.1125, 0.5685, 0.6508]])

### torch.normal
#### mean is float, std is float  
torch.normal(mean, std, size, \*, out=None)  

In [77]:
torch.normal(mean=2, std=3, size=(1, 5))

tensor([[ 3.1106,  0.8640,  6.8128, -1.1986,  8.0743]])

#### mean is float, std is tensor
torch.normal(mean=0.0, std, *, out=None) 

In [76]:
torch.normal(mean=0.5, std=torch.arange(1., 6.))

tensor([1.6693, 2.9867, 3.4782, 3.2756, 7.3793])

#### mean is tensor, std is float  
torch.normal(mean, std=1.0, *, out=None)  

In [79]:
torch.normal(mean=torch.arange(1., 6.))

tensor([1.9557, 2.6027, 1.4790, 3.5888, 6.8464])

#### mean is tensor, std is tensor, and 两者的元素数量一致
torch.normal(mean, std, *, generator=None, out=None)  

In [83]:
torch.normal(mean=torch.arange(1., 6.), std=torch.arange(1, 0, -0.2))

tensor([-0.3819,  2.2231,  4.2730,  4.5564,  5.4564])

## 多项式分布

### torch.multinomial
torch.multinomial(input, num_samples, replacement=False, \*, generator=None, out=None)
基于多项式分布，从input中随机抽取num_samples元素，并返回其索引
- input的每行之和无需一定为1, 但必须是大于0的有限数
- replacement=False 表示无重复抽取, 0 < num_samples <= len(input[0])
- replacement=True 表示可重复抽取, num_samples > 0

In [84]:
torch.multinomial(torch.tensor([[0., 10., 3.],[4., 2., 8.]]), 2)

tensor([[2, 1],
        [2, 1]])

In [85]:
torch.multinomial(torch.tensor([[0., 10., 3.],[4., 2., 8.]]), 3)

tensor([[1, 2, 0],
        [2, 0, 1]])

In [87]:
torch.multinomial(torch.tensor([[0., 10., 3.],[4., 2., 8.]]), 4, replacement=True)

tensor([[1, 1, 1, 1],
        [0, 2, 0, 2]])

## 0-1分布

### torch.bernoulli
torch.bernoulli(input, *, generator=None, out=None)  
input的每个元素都必须在[0,1]内

In [90]:
torch.bernoulli(torch.rand(2, 3))

tensor([[0., 1., 0.],
        [1., 1., 1.]])

## 泊松分布

### torch.poisson
torch.poisson(input, generator=None)

In [92]:
torch.poisson(torch.rand(2, 3) * 5)

tensor([[1., 3., 1.],
        [7., 3., 6.]])

# Indexing, Slicing, Joining, Mutating操作

## 形状

In [6]:
tensor_1 = torch.arange(1, 9, dtype=torch.float).reshape(2, 4)
print(tensor_1)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])


### torch.numel 元素数量

In [7]:
print("total number of elements =", tensor_1.numel() )
print("total number of elements =", torch.numel(tensor_1) )

total number of elements = 8
total number of elements = 8


### shape, size, dim

In [8]:
print("size:", tensor_1.shape)
print("size:", tensor_1.size())

print("total number of dimensions =", tensor_1.dim() )

print("size of 0-th dim =", tensor_1.shape[0] )
print("size of 0-th dim =", tensor_1.size(0) )
print("size of 0-th dim =", tensor_1.size()[0] )

size: torch.Size([2, 4])
size: torch.Size([2, 4])
total number of dimensions = 2
size of 0-th dim = 2
size of 0-th dim = 2
size of 0-th dim = 2


## 查找/索引 todo
不会开辟新内存

In [9]:
tensor_1 = torch.arange(1, 9, dtype=torch.float).reshape(2, 4)
print(tensor_1)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])


In [10]:
print("first element:", tensor_1[0][0].item() )
print("first element:", tensor_1[0,0].item() )
print("first row:",     tensor_1[0] )
print("Last column:",   tensor_1[:,-1] )
print("Last column:",   tensor_1[...,-1] )

first element: 1.0
first element: 1.0
first row: tensor([1., 2., 3., 4.])
Last column: tensor([4., 8.])
Last column: tensor([4., 8.])


>Notice: 索引返回的结果与原数据共享内存，也即修改一个，另一个会跟着修改

In [11]:
tensor_1[:,1] = 0
tensor_1

tensor([[1., 0., 3., 4.],
        [5., 0., 7., 8.]])

### torch.take
torch.take(input, index)

In [120]:
torch.take(tensor_1, torch.tensor([0,2,5,7]))

tensor([1., 3., 0., 8.])

### torch.take_along_dim
torch.take_along_dim(input, indices, dim, \*, out=None)  
input and indices should have the same number of dimensions

In [159]:
tensor_1 = torch.tensor([[4,2,3,1],[5,7,6,8]], dtype=torch.float)

In [160]:
tensor_1

tensor([[4., 2., 3., 1.],
        [5., 7., 6., 8.]])

In [161]:
sorted_idx = torch.argsort(tensor_1, dim=1)

In [162]:
sorted_idx

tensor([[3, 1, 2, 0],
        [0, 2, 1, 3]])

In [163]:
torch.take_along_dim(tensor_1, sorted_idx, dim=1)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

### torch.masked_select
torch.masked_select(input, mask, \*, out=None)  
Returns a new 1-D tensor which indexes the input tensor according to the boolean mask mask which is a BoolTensor.  
返回mask为真的元素组成的一维张量

In [164]:
tensor_1 = torch.tensor([[4,2,3,1],[5,7,6,8]], dtype=torch.float)

In [165]:
tensor_1

tensor([[4., 2., 3., 1.],
        [5., 7., 6., 8.]])

In [166]:
mask = torch.tensor([[True,False,True,False],[False,True,False,True]])

In [167]:
torch.masked_select(tensor_1, mask)

tensor([4., 3., 7., 8.])

### torch.nonzero
torch.nonzero(input, \*, out=None, as_tuple=False)  
**返回非0位置索引**。 如果as_tuple=False, 索引存成多维数组的形式; 如果as_tuple=True, 每个维度的索引存至不同的tensor中。

In [169]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]))

tensor([[0],
        [1],
        [2],
        [4]])

In [172]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]), as_tuple=True)

(tensor([0, 1, 2, 4]),)

In [173]:
torch.nonzero(torch.tensor([[0.6, 0.0],[0.0, 0.4],[0.0, 0.0],[0.0, -0.4]]))

tensor([[0, 0],
        [1, 1],
        [3, 1]])

In [174]:
torch.nonzero(torch.tensor([[0.6, 0.0],[0.0, 0.4],[0.0, 0.0],[0.0, -0.4]]), as_tuple=True)

(tensor([0, 1, 3]), tensor([0, 1, 1]))

### torch.where
torch.where(condition, input, other, *, out=None)  
$$ out_i = \begin{cases} \begin{array}{l,l}
input_i, & condition_i = True \\
other_i, & otherwise \\
\end{array} \end{cases} $$

Parameters:
- condition (BoolTensor) – When True (nonzero), yield input, otherwise yield other
- input (Tensor or Scalar) – value (if input is a scalar) or values selected at indices where condition is True
- other (Tensor or Scalar) – value (if other is a scalar) or values selected at indices where condition is False

In [178]:
tensor_1 = torch.tensor([[-0.462, 0.3139],[0.3898, -0.7197]], dtype=torch.float64)
tensor_2 = torch.zeros_like(tensor_1)

In [180]:
tensor_1

tensor([[-0.4620,  0.3139],
        [ 0.3898, -0.7197]], dtype=torch.float64)

In [179]:
torch.where(tensor_1 > 0, 1.0, 0.0)

tensor([[0., 1.],
        [1., 0.]])

In [182]:
torch.where(tensor_1 > 0, tensor_1, 1.0)

tensor([[1.0000, 0.3139],
        [0.3898, 1.0000]], dtype=torch.float64)

In [183]:
torch.where(tensor_1 > 0, tensor_1, tensor_2)

tensor([[0.0000, 0.3139],
        [0.3898, 0.0000]], dtype=torch.float64)

## 变形

### reshape, view
torch.reshape(input, shape)   
$\iff$ tensor_1.reshape(shape)  
$\iff$ tensor_1.view(shape)  

In [56]:
tensor_1 = torch.arange(1, 25)
print(tensor_1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])


In [ ]:
"""
torch.reshape(tensor_1, (2, 3, 4))
tensor_1.reshape(2, 3, 4)
tensor_1.view(2, 3, 4)
"""

In [463]:
torch.reshape(tensor_1, (2, 3, 4))

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [57]:
torch.equal(torch.reshape(tensor_1, (2, 3, 4)),
            tensor_1.reshape(2, 3, 4))

True

In [58]:
torch.equal(torch.reshape(tensor_1, (2, 3, 4)),
            tensor_1.view(2, 3, 4))

True

In [466]:
tensor_1.reshape((8, -1)) # -1 表示24/8

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]])

In [467]:
tensor_1.reshape((-1, 4)) # -1 表示24/4

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])

In [468]:
tensor_1.reshape((2, -1, 4)) # -1 表示24/2/4

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [ ]:
"""
tensor_1.reshape(tensor_1.numel())
tensor_1.reshape((tensor_1.numel()))
tensor_1.reshape(-1)
tensor_1.reshape((-1))
"""

In [66]:
tensor_1.reshape(tensor_1.numel())

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

In [67]:
torch.equal(tensor_1.reshape(tensor_1.numel()),
            tensor_1.reshape((tensor_1.numel())))

True

In [68]:
torch.equal(tensor_1.reshape(tensor_1.numel()),
            tensor_1.reshape(-1))

True

In [69]:
torch.equal(tensor_1.reshape(tensor_1.numel()),
            tensor_1.reshape((-1)))

True

>**变形虽然生成新的tensor，但是与源Tensor共享数据<br>即改变一个变形中的数值，所有tensor的数值一起发生变化**

In [72]:
tensor_1 = torch.arange(1, 25)
print(tensor_1, "\nid =", id(tensor_1))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24]) 
id = 140268886521792


In [73]:
tensor_2 = torch.reshape(tensor_1, (2, 3, 4))
print(tensor_2, "\nid =", id(tensor_2))

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]) 
id = 140268886572624


In [74]:
tensor_3 = tensor_1.view(4, 6) 
print(tensor_3, "\nid =", id(tensor_3))

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]) 
id = 140268891771184


In [75]:
tensor_2 -= 12
print(tensor_1)
print(tensor_2)
print(tensor_3)

tensor([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12])
tensor([[[-11, -10,  -9,  -8],
         [ -7,  -6,  -5,  -4],
         [ -3,  -2,  -1,   0]],

        [[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]]])
tensor([[-11, -10,  -9,  -8,  -7,  -6],
        [ -5,  -4,  -3,  -2,  -1,   0],
        [  1,   2,   3,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12]])


>**如果不想修改源tensor，需要将源tensor深拷贝后再进行变形<br>即深拷贝后再修改变形的数值，则不会影响源tensor数值**

In [76]:
print(tensor_1, "\nid =", id(tensor_1))

tensor([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12]) 
id = 140268886521792


In [77]:
tensor_4 = tensor_1.clone().view(3, 8)
print(tensor_4, "\nid =", id(tensor_4))

tensor([[-11, -10,  -9,  -8,  -7,  -6,  -5,  -4],
        [ -3,  -2,  -1,   0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9,  10,  11,  12]]) 
id = 140268897974688


In [78]:
tensor_4 += 12
print(tensor_1)
print(tensor_4)

tensor([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])


### torch.clone 深拷贝
torch.clone(input, *, memory_format=torch.preserve_format)  

In [79]:
print(tensor_1, "\nid =", id(tensor_1))
tensor_2 = torch.clone(tensor_1)
print(tensor_2, "\nid =", id(tensor_2))

tensor([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12]) 
id = 140268886521792
tensor([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9,  10,  11,  12]) 
id = 140268885109632


## 降维/升维

### torch.squeeze
torch.squeeze(input, dim=None)  
**删除所有size = 1的维度，或者如果指定维度dim的 size = 1, 则将该维度移除, 否则保持不变**

In [232]:
tensor_1 = torch.zeros(2, 1, 3, 1, 2)

In [233]:
tensor_1.size()

torch.Size([2, 1, 3, 1, 2])

In [234]:
torch.squeeze(tensor_1).size()

torch.Size([2, 3, 2])

In [235]:
torch.squeeze(tensor_1, dim=0).size()

torch.Size([2, 1, 3, 1, 2])

In [236]:
torch.squeeze(tensor_1, dim=1).size()

torch.Size([2, 3, 1, 2])

### torch.unsqueeze
torch.unsqueeze(input, dim)   
**在指定位置插入大小为1的维度**  
A dim value within the range $[-input.dim() - 1, input.dim() + 1)$ can be used. Negative dim will correspond to unsqueeze() applied at dim = dim + input.dim() + 1.

In [242]:
for index in range(-tensor_1.dim()-1, tensor_1.dim()+1):
    print("dim =",index, ":", torch.unsqueeze(tensor_1, dim=index).size() )

dim = -6 : torch.Size([1, 2, 1, 3, 1, 2])
dim = -5 : torch.Size([2, 1, 1, 3, 1, 2])
dim = -4 : torch.Size([2, 1, 1, 3, 1, 2])
dim = -3 : torch.Size([2, 1, 3, 1, 1, 2])
dim = -2 : torch.Size([2, 1, 3, 1, 1, 2])
dim = -1 : torch.Size([2, 1, 3, 1, 2, 1])
dim = 0 : torch.Size([1, 2, 1, 3, 1, 2])
dim = 1 : torch.Size([2, 1, 1, 3, 1, 2])
dim = 2 : torch.Size([2, 1, 1, 3, 1, 2])
dim = 3 : torch.Size([2, 1, 3, 1, 1, 2])
dim = 4 : torch.Size([2, 1, 3, 1, 1, 2])
dim = 5 : torch.Size([2, 1, 3, 1, 2, 1])


## 变形/转置 
### transpose, swapaxes, swapdims
1. torch.transpose(input, dim0, dim1)
2. torch.swapaxes(input, dim0, dim1)
3. torch.swapdims(input, dim0, dim1)  
**dim0 与 dim1 维度交换**

In [271]:
tensor_1 = torch.arange(1, 121).reshape(2, 3, 4, 5)

In [ ]:
"""
torch.transpose(tensor_1, dim0=0, dim1=2)
torch.transpose(tensor_1, dim0=2, dim1=0)
torch.swapaxes(tensor_1, axis0=0, axis1=2)
torch.swapdims(tensor_1, dim0=0, dim1=2)
"""

In [272]:
torch.transpose(tensor_1, dim0=0, dim1=2).size()

torch.Size([4, 3, 2, 5])

In [273]:
torch.equal(torch.transpose(tensor_1, dim0=0, dim1=2),
            torch.transpose(tensor_1, dim0=2, dim1=0))

True

In [274]:
torch.equal(torch.transpose(tensor_1, dim0=0, dim1=2),
            torch.swapaxes(tensor_1, axis0=0, axis1=2))

True

In [275]:
torch.equal(torch.transpose(tensor_1, dim0=0, dim1=2),
            torch.swapdims(tensor_1, dim0=0, dim1=2))

True

### movedim, moveaxis
1. torch.movedim(input, source, destination)
2. torch.moveaxis(input, source, destination)  
**move source-th dim to destination-th dim**

In [ ]:
"""
torch.movedim(tensor_1, 0, 2)
torch.moveaxis(tensor_1, 0, 2)
"""

In [277]:
torch.movedim(tensor_1, 0, 2).size()

torch.Size([3, 4, 2, 5])

In [279]:
torch.equal(torch.movedim(tensor_1, 0, 2),
            torch.moveaxis(tensor_1, 0, 2))

True

In [278]:
torch.equal(torch.transpose(tensor_1, dim0=0, dim1=2),
            torch.movedim(tensor_1, 0, 2))

False

In [45]:
torch.movedim(tensor_1, (1, 2), (0, 3)).size()

torch.Size([3, 2, 5, 4])

### torch.t
torch.t(input)  
1. 0-D and 1-D tensors are returned as is. 
2. When input is a 2-D tensor this is equivalent to transpose(input, 0, 1).

* 一维

In [97]:
torch.t(torch.tensor([1,2,3]))

tensor([1, 2, 3])

* 二维

In [ ]:
"""
torch.t(torch.tensor([[1,2,3],[4,5,6]]))
torch.tensor([[1,2,3],[4,5,6]]).T
torch.transpose(torch.tensor([[1,2,3],[4,5,6]]), 0, 1)
"""

In [98]:
torch.t(torch.tensor([[1,2,3],[4,5,6]]))

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [103]:
torch.equal(torch.t(torch.tensor([[1,2,3],[4,5,6]])),
            torch.tensor([[1,2,3],[4,5,6]]).T)

True

In [100]:
torch.equal(torch.t(torch.tensor([[1,2,3],[4,5,6]])),
            torch.transpose(torch.tensor([[1,2,3],[4,5,6]]), 0, 1))

True

## 拼接

In [80]:
tensor_1 = torch.arange(1, 4)
tensor_2 = torch.arange(4, 7)
tensor_3 = torch.arange(1, 7).reshape(2, 3)
tensor_4 = torch.arange(7, 13).reshape(2, 3)

### 水平拼接 cat, hstack, column_stack
1. torch.cat(tensors, dim=0, \*, out=None)  
2. torch.hstack(tensors, \*, out=None) 二维或多维张量沿着dim=1拼接，一维张量沿着dim=0拼接  
3. torch.column_stack(tensors, \*, out=None) 二维或多维张量沿着dim=1拼接，一维张量转置成列向量，再沿着dim=1拼接  

* 一维

In [81]:
print(tensor_1)
print(tensor_2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [ ]:
"""
torch.cat((tensor_1, tensor_2), dim=0)
torch.hstack((tensor_1, tensor_2))
"""

In [398]:
torch.cat((tensor_1, tensor_2), dim=0)

tensor([1, 2, 3, 4, 5, 6])

In [83]:
torch.equal(torch.cat((tensor_1, tensor_2), dim=0),
            torch.hstack((tensor_1, tensor_2)))

True

In [ ]:
"""
torch.column_stack((tensor_1, tensor_2))
torch.cat((tensor_1.reshape(tensor_1.numel(),1), tensor_2.reshape(tensor_2.numel(),1)), dim=1)
torch.stack((tensor_1, tensor_2), dim=1)
"""

In [400]:
torch.column_stack((tensor_1, tensor_2))

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [86]:
torch.equal(torch.column_stack((tensor_1, tensor_2)),
            torch.cat((tensor_1.reshape(tensor_1.numel(),1), tensor_2.reshape(tensor_2.numel(),1)), dim=1))

True

In [85]:
torch.equal(torch.column_stack((tensor_1, tensor_2)),
            torch.stack((tensor_1, tensor_2), dim=1))

True

* 二维

In [403]:
print(tensor_3)
print(tensor_4)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [ ]:
"""
torch.cat((tensor_3, tensor_4), dim=1)
torch.hstack((tensor_3, tensor_4))
torch.column_stack((tensor_3, tensor_4))
"""

In [404]:
torch.cat((tensor_3, tensor_4), dim=1)

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

In [87]:
torch.equal(torch.cat((tensor_3, tensor_4), dim=1),
            torch.hstack((tensor_3, tensor_4)))

True

In [88]:
torch.equal(torch.cat((tensor_3, tensor_4), dim=1),
            torch.column_stack((tensor_3, tensor_4)))

True

### 垂直拼接 cat, vstack, row_stack
1. torch.cat(tensors, dim=0, \*, out=None)  
2. torch.vstack(tensors, \*, out=None) $\iff$ torch.row_stack(tensors, *, out=None)

* 一维

In [92]:
print(tensor_1)
print(tensor_2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [ ]:
"""
torch.vstack((tensor_1, tensor_2))
torch.row_stack((tensor_1, tensor_2))
torch.stack((tensor_1, tensor_2), dim=0)
"""

In [93]:
torch.vstack((tensor_1, tensor_2))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [94]:
torch.equal(torch.vstack((tensor_1, tensor_2)),
            torch.row_stack((tensor_1, tensor_2)))

True

In [95]:
torch.equal(torch.vstack((tensor_1, tensor_2)),
            torch.stack((tensor_1, tensor_2), dim=0))

True

* 二维

In [411]:
print(tensor_3)
print(tensor_4)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [ ]:
"""
torch.cat((tensor_3, tensor_4), dim=0)
torch.vstack((tensor_3, tensor_4))
torch.row_stack((tensor_3, tensor_4))
"""

In [96]:
torch.cat((tensor_3, tensor_4), dim=0)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [97]:
torch.equal(torch.cat((tensor_3, tensor_4), dim=0),
            torch.vstack((tensor_3, tensor_4)))

True

In [98]:
torch.equal(torch.cat((tensor_3, tensor_4), dim=0),
            torch.row_stack((tensor_3, tensor_4)))

True

### 扩维拼接 stack, dstack
1. torch.cat(tensors, dim=0, \*, out=None) 沿着指定维度拼接，不增加维度
2. torch.stack(tensors, dim=0, \*, out=None) 先增加指定维度，再沿着新的维度拼接
3. torch.dstack(tensors, \*, out=None) 沿第三维(dim=2)拼接

* 一维

In [99]:
print(tensor_1)
print(tensor_2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [100]:
torch.stack((tensor_1, tensor_2), dim=0)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [101]:
torch.stack((tensor_1, tensor_2), dim=1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [102]:
torch.dstack((tensor_1, tensor_2))

tensor([[[1, 4],
         [2, 5],
         [3, 6]]])

In [103]:
torch.equal(torch.stack((tensor_1, tensor_2), dim=1),
            torch.dstack((tensor_1, tensor_2)))

False

* 二维

In [419]:
print(tensor_3)
print(tensor_4)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [420]:
torch.stack((tensor_3, tensor_4), dim=0)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [421]:
torch.stack((tensor_3, tensor_4), dim=1)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])

In [104]:
torch.stack((tensor_3, tensor_4), dim=2)

tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]])

In [105]:
torch.dstack((tensor_3, tensor_4))

tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]])

In [106]:
torch.equal(torch.stack((tensor_3, tensor_4), dim=2),
            torch.dstack((tensor_3, tensor_4)))

True

### torch.tile(input, dims) 维度复制
通过复制输入元素来构造张量。dims指定每个维度中的重复次数。

* 一维

In [424]:
print(tensor_1)

tensor([1, 2, 3])


In [425]:
torch.tile(tensor_1, (2,))

tensor([1, 2, 3, 1, 2, 3])

In [426]:
torch.tile(tensor_1, (2, 1))

tensor([[1, 2, 3],
        [1, 2, 3]])

In [427]:
torch.tile(tensor_1, (1, 2))

tensor([[1, 2, 3, 1, 2, 3]])

In [107]:
torch.equal(torch.tile(tensor_1, (2,)),
            torch.tile(tensor_1, (1, 2)))

False

In [428]:
torch.tile(tensor_1, (2, 2))

tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])

* 二维

In [108]:
torch.tile(tensor_3, (1, 1))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
"""
torch.tile(tensor_3, (2, 1))
torch.vstack((tensor_3, tensor_3))
tensor_3.tile((2, 1))
"""

In [109]:
torch.tile(tensor_3, (2, 1))

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]])

In [110]:
torch.equal(torch.tile(tensor_3, (2, 1)),
            torch.vstack((tensor_3, tensor_3)))

True

In [111]:
torch.equal(torch.tile(tensor_3, (2, 1)),
            tensor_3.tile((2, 1)))

True

In [ ]:
"""
torch.tile(tensor_3, (1, 2))
torch.tile(tensor_3, (2,))
torch.hstack((tensor_3, tensor_3))
"""

In [112]:
torch.tile(tensor_3, (1, 2))

tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]])

In [113]:
torch.equal(torch.tile(tensor_3, (1, 2)),
            torch.tile(tensor_3, (2,)))

True

In [114]:
torch.equal(torch.tile(tensor_3, (1, 2)),
            torch.hstack((tensor_3, tensor_3)))

True

In [436]:
torch.tile(tensor_3, (2, 2))

tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6],
        [1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]])

## 切块(chunk)

### torch.index_select
torch.index_select(input, dim, index, \*, out=None)  
**从tensor的dim维中，取指定index的所有元素**

* 二维

In [116]:
tensor_1 = torch.arange(1, 10).reshape(3, 3)

In [117]:
tensor_1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
"""
torch.index_select(tensor_1, dim=0, index=torch.tensor(1))
torch.index_select(tensor_1, dim=0, index=torch.tensor([1])
"""

In [123]:
torch.index_select(tensor_1, dim=0, index=torch.tensor(1))

tensor([[4, 5, 6]])

In [124]:
torch.equal(torch.index_select(tensor_1, dim=0, index=torch.tensor(1)),
            torch.index_select(tensor_1, dim=0, index=torch.tensor([1])))

True

In [120]:
torch.index_select(tensor_1, dim=0, index=torch.tensor([2, 1, 2]))

tensor([[7, 8, 9],
        [4, 5, 6],
        [7, 8, 9]])

In [121]:
torch.index_select(tensor_1, dim=1, index=torch.tensor(1))

tensor([[2],
        [5],
        [8]])

In [122]:
torch.index_select(tensor_1, dim=1, index=torch.tensor([2, 1, 2]))

tensor([[3, 2, 3],
        [6, 5, 6],
        [9, 8, 9]])

* 三维

In [491]:
tensor_2 = torch.arange(1, 25).reshape(2, 3, 4)

In [492]:
tensor_2

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [493]:
torch.index_select(tensor_2, dim=0, index=torch.tensor(1))

tensor([[[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [494]:
torch.index_select(tensor_2, dim=1, index=torch.tensor(1))

tensor([[[ 5,  6,  7,  8]],

        [[17, 18, 19, 20]]])

In [495]:
torch.index_select(tensor_2, dim=2, index=torch.tensor(1))

tensor([[[ 2],
         [ 6],
         [10]],

        [[14],
         [18],
         [22]]])

### torch.narrow
1. torch.narrow(input, dim, start, length)  
2. torch.narrow_copy(input, dim, start, length, \*, out=None)  
**从tensor的dim维中，取[start, start + length)的所有元素**

* 二维

In [496]:
torch.narrow(tensor_1, dim=0, start=1, length=2)

tensor([[4, 5, 6],
        [7, 8, 9]])

In [497]:
torch.narrow(tensor_1, dim=1, start=1, length=2)

tensor([[2, 3],
        [5, 6],
        [8, 9]])

* 三维

In [499]:
torch.narrow(tensor_2, dim=1, start=1, length=2)

tensor([[[ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [500]:
torch.narrow(tensor_2, dim=2, start=1, length=2)

tensor([[[ 2,  3],
         [ 6,  7],
         [10, 11]],

        [[14, 15],
         [18, 19],
         [22, 23]]])

### torch.unbind
torch.unbind(input, dim=0)  
**按指定维度dim切块**

In [250]:
tensor_1 = torch.tensor([[1,2,3],[4,5,6]])

In [251]:
torch.unbind(tensor_1, dim=0)

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [252]:
torch.unbind(tensor_1, dim=1)

(tensor([1, 4]), tensor([2, 5]), tensor([3, 6]))

### torch.split
torch.split(tensor, split_size_or_sections, dim=0)  
**按size切块**  
let split_size_or_sections = $x$,  
* if $x$ is int, 将tensor的dim维切分成若干块(chunk), 每块包含$x$个, 不足的放在最后一块;  
* if $x = [x_1, x_2, \dots, x_n]$, 将tensor的dim维切分成n个块(chunk), 第$i$个块包含$x_i$个

In [501]:
tensor_1 = torch.arange(10).reshape(-1, 2)
tensor_1

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [502]:
torch.split(tensor_1, 2, dim=0)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [504]:
torch.split(tensor_1, [1,2,2], dim=0)

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5]]),
 tensor([[6, 7],
         [8, 9]]))

### torch.tensor_split(input, indices_or_sections, dim=0)
**按索引切块**

In [130]:
tensor_1 = torch.arange(16).reshape(-1, 2)
tensor_1

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]])

let split_size_or_sections = $x$,<br>
* if $x$ is int or torch.tensor(int), 将tensor的dim维切分成$x$块

In [133]:
torch.tensor_split(tensor_1, 3, dim=0)

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[ 6,  7],
         [ 8,  9],
         [10, 11]]),
 tensor([[12, 13],
         [14, 15]]))

In [134]:
torch.tensor_split(tensor_1, torch.tensor(3), dim=0)

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[ 6,  7],
         [ 8,  9],
         [10, 11]]),
 tensor([[12, 13],
         [14, 15]]))

* if $x$ is list(int), tuple(int) or torch.tensor(list(int)), 将tensor的dim维按照int的索引切分成若干块

In [534]:
torch.tensor_split(tensor_1, [3], dim=0)

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[ 6,  7],
         [ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]))

In [535]:
torch.tensor_split(tensor_1, (3), dim=0)

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[ 6,  7],
         [ 8,  9],
         [10, 11]]),
 tensor([[12, 13],
         [14, 15]]))

In [536]:
torch.tensor_split(tensor_1, torch.tensor([3]), dim=0)

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[ 6,  7],
         [ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]))

In [537]:
torch.tensor_split(tensor_1, [0, 3], dim=0)

(tensor([], size=(0, 2), dtype=torch.int64),
 tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[ 6,  7],
         [ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]))

In [538]:
torch.tensor_split(tensor_1, (0, 3), dim=0)

(tensor([], size=(0, 2), dtype=torch.int64),
 tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[ 6,  7],
         [ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]))

In [539]:
torch.tensor_split(tensor_1, torch.tensor([0, 3]), dim=0)

(tensor([], size=(0, 2), dtype=torch.int64),
 tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[ 6,  7],
         [ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]))

### torch.chunk
torch.chunk(input, chunks, dim=0)  
let chunks = $x$, $x$ is int, **将tensor的dim维切成$x$块**
1. 如果沿着给定维度dim的张量大小可以被块整除，那么所有返回的块都将是相同的大小。
2. 如果沿着给定维度dim的张量大小不能被块整除，那么除了最后一个块之外，所有返回的块都将是相同的大小。
3. 如果不能进行这样的划分，则此函数可能返回少于指定数量的块。

In [541]:
tensor_1 = torch.arange(16).reshape(-1, 2)
tensor_1

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]])

In [547]:
for chunks in range(1,tensor_1.size(0)+1):
    print("\nchunks =", chunks)
    for elem in torch.chunk(tensor_1, chunks, dim=0):
        print(elem)


chunks = 1
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]])

chunks = 2
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
tensor([[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]])

chunks = 3
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])
tensor([[12, 13],
        [14, 15]])

chunks = 4
tensor([[0, 1],
        [2, 3]])
tensor([[4, 5],
        [6, 7]])
tensor([[ 8,  9],
        [10, 11]])
tensor([[12, 13],
        [14, 15]])

chunks = 5
tensor([[0, 1],
        [2, 3]])
tensor([[4, 5],
        [6, 7]])
tensor([[ 8,  9],
        [10, 11]])
tensor([[12, 13],
        [14, 15]])

chunks = 6
tensor([[0, 1],
        [2, 3]])
tensor([[4, 5],
        [6, 7]])
tensor([[ 8,  9],
        [10, 11]])
tensor([[12, 13],
        [14, 15]])

chunks = 7
tensor([[0, 1],
        [2, 3]])
tensor([[4, 5],
        [6, 7]])
tensor

# 数学运算

## torch.add 加法
torch.add(input, other, \*, alpha=1, out=None)
$$out_i = input_i + alpha \times other_i$$

In [66]:
tensorX = torch.arange(1, 7).reshape(2, 3)
tensorY = torch.ones_like(tensorX)
print(tensorX)
print(tensorY)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 1, 1],
        [1, 1, 1]])


In [67]:
torch.add(tensorX, tensorY, alpha=2)

tensor([[3, 4, 5],
        [6, 7, 8]])

### X数值不变, 内存不变, 开辟新的内存地址存储结果

In [68]:
tensorX = torch.arange(1, 7).reshape(2, 3)
tensorY = torch.ones_like(tensorX)
print(tensorX)
print(tensorY)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 1, 1],
        [1, 1, 1]])


In [69]:
print("before add: X =\n", tensorX, "\nid=", id(tensorX))
tensorZ = tensorX + tensorY
print("\nafter add: X =\n", tensorX, "\nid=", id(tensorX))
print('\nafter add: Z =\n', tensorZ, "\nid=", id(tensorZ))

before add: X =
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
id= 140415026638576

after add: X =
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
id= 140415026638576

after add: Z =
 tensor([[2, 3, 4],
        [5, 6, 7]]) 
id= 140415026230992


In [70]:
print("before add: X =\n", tensorX, "\nid=", id(tensorX))
tensorZ = torch.add(tensorX, tensorY)
print("\nafter add: X =\n", tensorX, "\nid=", id(tensorX))
print('\nafter add: Z =\n', tensorZ, "\nid=", id(tensorZ))

before add: X =
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
id= 140415026638576

after add: X =
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
id= 140415026638576

after add: Z =
 tensor([[2, 3, 4],
        [5, 6, 7]]) 
id= 140415026377488


In [71]:
print("before add: X =\n", tensorX, "\nid=", id(tensorX))
tensorZ = tensorX.add(tensorY)
print("\nafter add: X =\n", tensorX, "\nid=", id(tensorX))
print('\nafter add: Z =\n', tensorZ, "\nid=", id(tensorZ))

before add: X =
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
id= 140415026638576

after add: X =
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
id= 140415026638576

after add: Z =
 tensor([[2, 3, 4],
        [5, 6, 7]]) 
id= 140415026616576


### X数值改变, 内存改变 

In [72]:
tensorX = torch.arange(1, 7).reshape(2, 3)
tensorY = torch.ones_like(tensorX)
print(tensorX)
print(tensorY)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 1, 1],
        [1, 1, 1]])


In [73]:
print("before add: X =\n", tensorX, "\nid=", id(tensorX))
tensorX = tensorX + tensorY
print("\nafter add: X =\n", tensorX, "\nid=", id(tensorX))

before add: X =
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
id= 140415026637776

after add: X =
 tensor([[2, 3, 4],
        [5, 6, 7]]) 
id= 140415026230592


### X数值改变, 内存不变, 节约内存开销

In [74]:
tensorX = torch.arange(1, 7).reshape(2, 3)
tensorY = torch.ones_like(tensorX)
print(tensorX)
print(tensorY)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 1, 1],
        [1, 1, 1]])


In [75]:
print("before add: X =\n", tensorX, "\nid=", id(tensorX))
tensorX[:] = tensorX + tensorY
print("\nafter add: X =\n", tensorX, "\nid=", id(tensorX))

before add: X =
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
id= 140415026638736

after add: X =
 tensor([[2, 3, 4],
        [5, 6, 7]]) 
id= 140415026638736


In [76]:
print("before add: X =\n", tensorX, "\nid=", id(tensorX))
torch.add(tensorX, tensorY, out=tensorX)
print("\nafter add: X =\n", tensorX, "\nid=", id(tensorX))

before add: X =
 tensor([[2, 3, 4],
        [5, 6, 7]]) 
id= 140415026638736

after add: X =
 tensor([[3, 4, 5],
        [6, 7, 8]]) 
id= 140415026638736


In [77]:
print("before add: X =\n", tensorX, "\nid=", id(tensorX))
tensorX.add_(tensorY)
print("\nafter add: X =\n", tensorX, "\nid=", id(tensorX))

before add: X =
 tensor([[3, 4, 5],
        [6, 7, 8]]) 
id= 140415026638736

after add: X =
 tensor([[4, 5, 6],
        [7, 8, 9]]) 
id= 140415026638736


In [78]:
print("before add: X =\n", tensorX, "\nid=", id(tensorX))
tensorX += tensorY
print("\nafter add: X =\n", tensorX, "\nid=", id(tensorX))

before add: X =
 tensor([[4, 5, 6],
        [7, 8, 9]]) 
id= 140415026638736

after add: X =
 tensor([[ 5,  6,  7],
        [ 8,  9, 10]]) 
id= 140415026638736


### broadcasting
todo: https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics  
先适当复制元素使这两个Tensor形状相同后再按元素运算

In [83]:
print("X:", torch.arange(1, 4).reshape(3, 1))
print("Y:", torch.arange(1, 4))
print("X + Y =", torch.tensor([[1], [2], [3]]) + torch.tensor([1, 2, 3]))

X: tensor([[1],
        [2],
        [3]])
Y: tensor([1, 2, 3])
X + Y = tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])


In [84]:
torch.equal(torch.tensor([[1], [2], [3]]) + torch.tensor([1, 2, 3]),
            torch.tensor([1, 2, 3]) + torch.tensor([[1], [2], [3]]))

True

## 乘法

### torch.mul 点乘
1. torch.mul(input, other, *, out=None)
2. torch.multiply(input, other, *, out=None)

* tensor_1 is int

In [87]:
tensor_1 = torch.arange(1, 7).reshape(2, 3)
print(tensor_1)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
"""
tensor_1 * 3
tensor_1.mul(3)
torch.mul(tensor_1, 3)
torch.multiply(tensor_1, 3)
"""

In [248]:
tensor_1 * 3

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [249]:
torch.equal(tensor_1 * 3,
            tensor_1.mul(3))

True

In [250]:
torch.equal(tensor_1 * 3,
            torch.mul(tensor_1, 3))

True

In [251]:
torch.equal(tensor_1 * 3,
            torch.multiply(tensor_1, 3))

True

* other is Tensor

In [ ]:
"""
tensor_1 * tensor_1
tensor_1.mul(tensor_1)
torch.mul(tensor_1, tensor_1)
torch.multiply(tensor_1, tensor_1)
torch.mul(tensor_1, tensor_1, out=torch.zeros((tensor_1.shape[0], tensor_1.shape[1]), dtype=tensor_1.dtype))
"""

In [88]:
tensor_1 * tensor_1

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [89]:
torch.equal(tensor_1 * tensor_1,
            tensor_1.mul(tensor_1))

True

In [90]:
torch.equal(tensor_1 * tensor_1,
            torch.mul(tensor_1, tensor_1))

True

In [91]:
torch.equal(tensor_1 * tensor_1,
            torch.multiply(tensor_1, tensor_1))

True

In [92]:
torch.equal(tensor_1 * tensor_1,
            torch.mul(tensor_1, tensor_1, out=torch.zeros((tensor_1.shape[0], tensor_1.shape[1]), dtype=tensor_1.dtype)))

True

#### broadcasting

In [93]:
print("X:", torch.arange(1, 4).reshape(3, 1))
print("Y:", torch.arange(1, 4))
print("X * Y =", torch.tensor([[1], [2], [3]]) * torch.tensor([1, 2, 3]))

X: tensor([[1],
        [2],
        [3]])
Y: tensor([1, 2, 3])
X * Y = tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])


In [94]:
torch.equal(torch.tensor([[1], [2], [3]]) * torch.tensor([1, 2, 3]),
            torch.tensor([1, 2, 3]) * torch.tensor([[1], [2], [3]]))

True

### torch.matmul 矩阵乘法
torch.matmul(input, other, \*, out=None)

#### vector × vector
返回点乘之和

In [158]:
tensor_1 = torch.tensor([1, 2, 3])
tensor_1

tensor([1, 2, 3])

In [159]:
torch.matmul(tensor_1, tensor_1)

tensor(14)

In [160]:
torch.mul(tensor_1, tensor_1)

tensor([1, 4, 9])

In [161]:
torch.sum(torch.mul(tensor_1, tensor_1))

tensor(14)

#### matrix × vector
multiple vector $\times$ vector

In [245]:
tensor_1 = torch.arange(1, 7).reshape(2, 3)
tensor_2 = torch.tensor([1, 2, 3])
print("size of tensor_1 =", tensor_1.size())
print("size of tensor_2 =", tensor_2.size())
print("size of tensor_1 @ tensor_2 =", torch.matmul(tensor_1, tensor_2).size())

size of tensor_1 = torch.Size([2, 3])
size of tensor_2 = torch.Size([3])
size of tensor_1 @ tensor_2 = torch.Size([2])


In [163]:
torch.matmul(tensor_1, tensor_2)

tensor([14, 32])

In [165]:
for ii in range(tensor_1.size(0)):
    print(tensor_1[ii] @ tensor_2)

tensor(14)
tensor(32)


#### matrix × matrix

In [166]:
tensor_1 = torch.arange(1, 7).reshape(2, 3)
print(tensor_1)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
"""
tensor_1 @ tensor_1.T
tensor_1.matmul(tensor_1.T)
torch.matmul(tensor_1, tensor_1.T)
"""

In [167]:
tensor_1 @ tensor_1.T

tensor([[14, 32],
        [32, 77]])

In [168]:
torch.equal(tensor_1 @ tensor_1.T,
            tensor_1.matmul(tensor_1.T))

True

In [169]:
torch.equal(tensor_1 @ tensor_1.T,
            torch.matmul(tensor_1, tensor_1.T))

True

#### batched matrix × broadcasted vector

In [244]:
tensor_1 = torch.arange(1, 25).reshape(2, 3, 4)
tensor_2 = torch.arange(1, 5)
print("size of tensor_1 =", tensor_1.size())
print("size of tensor_2 =", tensor_2.size())
print("size of tensor_1 @ tensor_2 =", torch.matmul(tensor_1, tensor_2).size())

size of tensor_1 = torch.Size([2, 3, 4])
size of tensor_2 = torch.Size([4])
size of tensor_1 @ tensor_2 = torch.Size([2, 3])


In [171]:
torch.matmul(tensor_1, tensor_2)

tensor([[ 30,  70, 110],
        [150, 190, 230]])

In [172]:
for ii in range(tensor_1.size(0)):
    vec = []
    for jj in range(tensor_1[ii].size(0)):
        vec.append(tensor_1[ii][jj] @ tensor_2)
    print(vec)

[tensor(30), tensor(70), tensor(110)]
[tensor(150), tensor(190), tensor(230)]


#### batched matrix × broadcasted matrix

In [243]:
tensor_1 = torch.arange(1, 25).reshape(2, 3, 4)
tensor_2 = torch.arange(1, 21).reshape(4, 5)
print("size of tensor_1 =", tensor_1.size())
print("size of tensor_2 =", tensor_2.size())
print("size of tensor_1 @ tensor_2 =", torch.matmul(tensor_1, tensor_2).size())

size of tensor_1 = torch.Size([2, 3, 4])
size of tensor_2 = torch.Size([4, 5])
size of tensor_1 @ tensor_2 = torch.Size([2, 3, 5])


In [202]:
torch.matmul(tensor_1, tensor_2)

tensor([[[ 110,  120,  130,  140,  150],
         [ 246,  272,  298,  324,  350],
         [ 382,  424,  466,  508,  550]],

        [[ 518,  576,  634,  692,  750],
         [ 654,  728,  802,  876,  950],
         [ 790,  880,  970, 1060, 1150]]])

In [203]:
for ii in range(tensor_1.size(0)):
    print(tensor_1[ii] @ tensor_2)

tensor([[110, 120, 130, 140, 150],
        [246, 272, 298, 324, 350],
        [382, 424, 466, 508, 550]])
tensor([[ 518,  576,  634,  692,  750],
        [ 654,  728,  802,  876,  950],
        [ 790,  880,  970, 1060, 1150]])


#### batched matrix × batched matrix

In [242]:
tensor_1 = torch.arange(1, 25).reshape(2, 3, 4)
tensor_2 = torch.arange(1, 41).reshape(2, 4, 5)
print("size of tensor_1 =", tensor_1.size())
print("size of tensor_2 =", tensor_2.size())
print("size of tensor_1 @ tensor_2 =", torch.matmul(tensor_1, tensor_2).size())

size of tensor_1 = torch.Size([2, 3, 4])
size of tensor_2 = torch.Size([2, 4, 5])
size of tensor_1 @ tensor_2 = torch.Size([2, 3, 5])


In [225]:
torch.matmul(tensor_1, tensor_2)

tensor([[[ 110,  120,  130,  140,  150],
         [ 246,  272,  298,  324,  350],
         [ 382,  424,  466,  508,  550]],

        [[1678, 1736, 1794, 1852, 1910],
         [2134, 2208, 2282, 2356, 2430],
         [2590, 2680, 2770, 2860, 2950]]])

In [226]:
for ii in range(tensor_1.size(0)):
    print(tensor_1[ii] @ tensor_2[ii])

tensor([[110, 120, 130, 140, 150],
        [246, 272, 298, 324, 350],
        [382, 424, 466, 508, 550]])
tensor([[1678, 1736, 1794, 1852, 1910],
        [2134, 2208, 2282, 2356, 2430],
        [2590, 2680, 2770, 2860, 2950]])


#### broadcasting
* case 1<br>
if input is a $(j×1×n×n)$ tensor and other is a $(k×n×n)$ tensor, out will be a $(j×k×n×n)$ tensor.

In [236]:
tensor_1 = torch.arange(1, 3*4*4+1).reshape(3, 1, 4, 4)
tensor_2 = torch.arange(1, 2*4*4+1).reshape(2, 4, 4)
print("size of tensor_1 =", tensor_1.size())
print("size of tensor_2 =", tensor_2.size())
print("size of tensor_1 @ tensor_2 =", torch.matmul(tensor_1, tensor_2).size())

size of tensor_1 = torch.Size([3, 1, 4, 4])
size of tensor_2 = torch.Size([2, 4, 4])
size of tensor_1 @ tensor_2 = torch.Size([3, 2, 4, 4])


In [237]:
torch.matmul(tensor_1, tensor_2)

tensor([[[[  90,  100,  110,  120],
          [ 202,  228,  254,  280],
          [ 314,  356,  398,  440],
          [ 426,  484,  542,  600]],

         [[ 250,  260,  270,  280],
          [ 618,  644,  670,  696],
          [ 986, 1028, 1070, 1112],
          [1354, 1412, 1470, 1528]]],


        [[[ 538,  612,  686,  760],
          [ 650,  740,  830,  920],
          [ 762,  868,  974, 1080],
          [ 874,  996, 1118, 1240]],

         [[1722, 1796, 1870, 1944],
          [2090, 2180, 2270, 2360],
          [2458, 2564, 2670, 2776],
          [2826, 2948, 3070, 3192]]],


        [[[ 986, 1124, 1262, 1400],
          [1098, 1252, 1406, 1560],
          [1210, 1380, 1550, 1720],
          [1322, 1508, 1694, 1880]],

         [[3194, 3332, 3470, 3608],
          [3562, 3716, 3870, 4024],
          [3930, 4100, 4270, 4440],
          [4298, 4484, 4670, 4856]]]])

In [238]:
for ii in range(tensor_1.size(0)):
    for jj in range(tensor_2.size(0)):
        print(tensor_1[ii][0] @ tensor_2[jj])

tensor([[ 90, 100, 110, 120],
        [202, 228, 254, 280],
        [314, 356, 398, 440],
        [426, 484, 542, 600]])
tensor([[ 250,  260,  270,  280],
        [ 618,  644,  670,  696],
        [ 986, 1028, 1070, 1112],
        [1354, 1412, 1470, 1528]])
tensor([[ 538,  612,  686,  760],
        [ 650,  740,  830,  920],
        [ 762,  868,  974, 1080],
        [ 874,  996, 1118, 1240]])
tensor([[1722, 1796, 1870, 1944],
        [2090, 2180, 2270, 2360],
        [2458, 2564, 2670, 2776],
        [2826, 2948, 3070, 3192]])
tensor([[ 986, 1124, 1262, 1400],
        [1098, 1252, 1406, 1560],
        [1210, 1380, 1550, 1720],
        [1322, 1508, 1694, 1880]])
tensor([[3194, 3332, 3470, 3608],
        [3562, 3716, 3870, 4024],
        [3930, 4100, 4270, 4440],
        [4298, 4484, 4670, 4856]])


* case 2<br>
if input is a $(j×1×n×m)$ tensor and other is a $(k×m×p)$ tensor, out will be a $(j×k×n×p)$ tensor.

In [239]:
tensor_1 = torch.arange(1, 3*4*5+1).reshape(3, 1, 4, 5)
tensor_2 = torch.arange(1, 2*5*6+1).reshape(2, 5, 6)
print("size of tensor_1 =", tensor_1.size())
print("size of tensor_2 =", tensor_2.size())
print("size of tensor_1 @ tensor_2 =", torch.matmul(tensor_1, tensor_2).size())

size of tensor_1 = torch.Size([3, 1, 4, 5])
size of tensor_2 = torch.Size([2, 5, 6])
size of tensor_1 @ tensor_2 = torch.Size([3, 2, 4, 6])


In [232]:
torch.matmul(tensor_1, tensor_2)

tensor([[[[  255,   270,   285,   300,   315,   330],
          [  580,   620,   660,   700,   740,   780],
          [  905,   970,  1035,  1100,  1165,  1230],
          [ 1230,  1320,  1410,  1500,  1590,  1680]],

         [[  705,   720,   735,   750,   765,   780],
          [ 1780,  1820,  1860,  1900,  1940,  1980],
          [ 2855,  2920,  2985,  3050,  3115,  3180],
          [ 3930,  4020,  4110,  4200,  4290,  4380]]],


        [[[ 1555,  1670,  1785,  1900,  2015,  2130],
          [ 1880,  2020,  2160,  2300,  2440,  2580],
          [ 2205,  2370,  2535,  2700,  2865,  3030],
          [ 2530,  2720,  2910,  3100,  3290,  3480]],

         [[ 5005,  5120,  5235,  5350,  5465,  5580],
          [ 6080,  6220,  6360,  6500,  6640,  6780],
          [ 7155,  7320,  7485,  7650,  7815,  7980],
          [ 8230,  8420,  8610,  8800,  8990,  9180]]],


        [[[ 2855,  3070,  3285,  3500,  3715,  3930],
          [ 3180,  3420,  3660,  3900,  4140,  4380],
          [ 3505

In [233]:
for ii in range(tensor_1.size(0)):
    for jj in range(tensor_2.size(0)):
        print(tensor_1[ii][0] @ tensor_2[jj])

tensor([[ 255,  270,  285,  300,  315,  330],
        [ 580,  620,  660,  700,  740,  780],
        [ 905,  970, 1035, 1100, 1165, 1230],
        [1230, 1320, 1410, 1500, 1590, 1680]])
tensor([[ 705,  720,  735,  750,  765,  780],
        [1780, 1820, 1860, 1900, 1940, 1980],
        [2855, 2920, 2985, 3050, 3115, 3180],
        [3930, 4020, 4110, 4200, 4290, 4380]])
tensor([[1555, 1670, 1785, 1900, 2015, 2130],
        [1880, 2020, 2160, 2300, 2440, 2580],
        [2205, 2370, 2535, 2700, 2865, 3030],
        [2530, 2720, 2910, 3100, 3290, 3480]])
tensor([[5005, 5120, 5235, 5350, 5465, 5580],
        [6080, 6220, 6360, 6500, 6640, 6780],
        [7155, 7320, 7485, 7650, 7815, 7980],
        [8230, 8420, 8610, 8800, 8990, 9180]])
tensor([[2855, 3070, 3285, 3500, 3715, 3930],
        [3180, 3420, 3660, 3900, 4140, 4380],
        [3505, 3770, 4035, 4300, 4565, 4830],
        [3830, 4120, 4410, 4700, 4990, 5280]])
tensor([[ 9305,  9520,  9735,  9950, 10165, 10380],
        [10380, 10620, 

* case 3

In [240]:
tensor_1 = torch.arange(1, 3*4*4+1).reshape(3, 4, 4)
tensor_2 = torch.arange(1, 2*4*4+1).reshape(2, 4, 4)
print("size of tensor_1 =", tensor_1.size())
print("size of tensor_2 =", tensor_2.size())
print("size of tensor_1 @ tensor_2 =", torch.matmul(tensor_1, tensor_2).size())

size of tensor_1 = torch.Size([3, 4, 4])
size of tensor_2 = torch.Size([2, 4, 4])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

In [241]:
tensor_1 = torch.unsqueeze(torch.arange(1, 3*4*4+1).reshape(3, 4, 4), dim = 1)
tensor_2 = torch.arange(1, 2*4*4+1).reshape(2, 4, 4)
print("size of tensor_1 =", tensor_1.size())
print("size of tensor_2 =", tensor_2.size())
print("size of tensor_1 @ tensor_2 =", torch.matmul(tensor_1, tensor_2).size())

size of tensor_1 = torch.Size([3, 1, 4, 4])
size of tensor_2 = torch.Size([2, 4, 4])
size of tensor_1 @ tensor_2 = torch.Size([3, 2, 4, 4])


### torch.addcmul
torch.addcmul(input, tensor1, tensor2, *, value=1, out=None)
$$ out_i = input_i + value \times tensor1_i \times tensor2_i $$

In [350]:
torch.addcmul(input=torch.tensor([4.,5.]),
              tensor1=torch.tensor([1.,2.]),
              tensor2=torch.tensor([3.,2.]),
              value=2)

tensor([10., 13.])

In [351]:
torch.tensor([4.,5.]).addcmul(tensor1=torch.tensor([1.,2.]),
                              tensor2=torch.tensor([3.,2.]),
                              value=2)

tensor([10., 13.])

## 除法

### torch.div 除法
torch.div(input, other, \*, rounding_mode=None, out=None)  
$\iff$ torch.divide(input, other, *, rounding_mode=None, out=None)
1. rounding_mode=None: 四舍五入 $\iff$ torch.true_divide(dividend, divisor, *, out) 
2. rounding_mode="trunc": 向0取整
3. rounding_mode="floor": 向下取整

* other is int, rounding_mode=None

In [ ]:
"""
torch.div(torch.tensor([-4., 1., 4.]), 3)
torch.divide(torch.tensor([-4., 1., 4.]), 3)
torch.true_divide(torch.tensor([-4., 1., 4.]), 3)
torch.tensor([-4., 1., 4.]).div(3)
torch.tensor([-4., 1., 4.]).divide(3)
torch.tensor([-4., 1., 4.]).true_divide(3)
"""

In [312]:
torch.div(torch.tensor([-4., 1., 4.]), 3)

tensor([-1.3333,  0.3333,  1.3333])

In [313]:
torch.divide(torch.tensor([-4., 1., 4.]), 3)

tensor([-1.3333,  0.3333,  1.3333])

In [314]:
torch.true_divide(torch.tensor([-4., 1., 4.]), 3)

tensor([-1.3333,  0.3333,  1.3333])

In [315]:
torch.tensor([-4., 1., 4.]).div(3)

tensor([-1.3333,  0.3333,  1.3333])

In [316]:
torch.tensor([-4., 1., 4.]).divide(3)

tensor([-1.3333,  0.3333,  1.3333])

In [317]:
torch.tensor([-4., 1., 4.]).true_divide(3)

tensor([-1.3333,  0.3333,  1.3333])

* other is int, rounding_mode="trunc"

In [306]:
torch.div(torch.tensor([-4., 1., 4.]), 3, rounding_mode="trunc")

tensor([-1.,  0.,  1.])

* other is int, rounding_mode="floor"

In [307]:
torch.div(torch.tensor([-4., 1., 4.]), 3, rounding_mode="floor")

tensor([-2.,  0.,  1.])

* other is Tensor

In [261]:
tensor_1 = torch.arange(-6, 6).reshape(4, 3)
tensor_2 = torch.ones(3, dtype=torch.int) * 3

In [265]:
torch.div(tensor_1, tensor_2)

tensor([[-2.0000, -1.6667, -1.3333],
        [-1.0000, -0.6667, -0.3333],
        [ 0.0000,  0.3333,  0.6667],
        [ 1.0000,  1.3333,  1.6667]])

In [267]:
for ii in range(tensor_1.size(0)):
    print(tensor_1[ii].div(tensor_2))

tensor([-2.0000, -1.6667, -1.3333])
tensor([-1.0000, -0.6667, -0.3333])
tensor([0.0000, 0.3333, 0.6667])
tensor([1.0000, 1.3333, 1.6667])


### torch.addcdiv
torch.addcdiv(input, tensor1, tensor2, *, value=1, out=None)
$$ out_i = input_i + value \times \frac{tensor1_i}{tensor2_i} $$

In [353]:
torch.addcdiv(input=torch.tensor([4.,5.]),
              tensor1=torch.tensor([3.,4.]),
              tensor2=torch.tensor([2.,3.]),
              value=2)

tensor([7.0000, 7.6667])

In [354]:
torch.tensor([4.,5.]).addcdiv(tensor1=torch.tensor([3.,4.]),
                              tensor2=torch.tensor([2.,3.]),
                              value=2)

tensor([7.0000, 7.6667])

## 绝对值/近似

In [280]:
tensor_1 = torch.tensor([-4.2, -0.1, 0.2, 4.6])

### torch.abs 绝对值
torch.abs(input, \*, out=None)  
$\iff$ torch.absolute(input, \*, out=None)

In [ ]:
"""
torch.abs(tensor_1)
tensor_1.abs()
torch.absolute(tensor_1)
tensor_1.absolute()
"""

In [281]:
torch.abs(tensor_1)

tensor([4.2000, 0.1000, 0.2000, 4.6000])

In [282]:
tensor_1.abs()

tensor([4.2000, 0.1000, 0.2000, 4.6000])

In [283]:
torch.absolute(tensor_1)

tensor([4.2000, 0.1000, 0.2000, 4.6000])

In [284]:
tensor_1.absolute()

tensor([4.2000, 0.1000, 0.2000, 4.6000])

### torch.round 四舍五入
torch.round(input, \*, decimals=0, out=None)  

In [319]:
torch.round(tensor_1)

tensor([-4., -0.,  0.,  5.])

>**notice**: 与两个整数等距的值, 四舍五入到最近的偶数值<br>
Values equidistant from two integers are rounded towards the nearest even value 

In [323]:
tensor_2 = torch.arange(-2.5, 3.0, step=1)
print(tensor_2)

tensor([-2.5000, -1.5000, -0.5000,  0.5000,  1.5000,  2.5000])


In [324]:
torch.round(tensor_2)

tensor([-2., -2., -0.,  0.,  2.,  2.])

In [320]:
torch.round(torch.tensor([0.1234567]), decimals=3)

tensor([0.1230])

In [321]:
torch.round(torch.tensor([1200.1234567]), decimals=-3)

tensor([1000.])

### torch.ceil 向上取整
torch.ceil(input, *, out=None)

In [286]:
print(tensor_1)

tensor([-4.2000, -0.1000,  0.2000,  4.6000])


In [285]:
torch.ceil(tensor_1)

tensor([-4., -0.,  1.,  5.])

In [287]:
tensor_1.ceil()

tensor([-4., -0.,  1.,  5.])

### torch.floor 向下取整
torch.floor(input, *, out=None)

In [288]:
torch.floor(tensor_1)

tensor([-5., -1.,  0.,  4.])

In [289]:
tensor_1.floor()

tensor([-5., -1.,  0.,  4.])

### torch.trunc 向0取整
torch.trunc(input, \*, out=None)  
$\iff$ torch.fix(input, \*, out=None)

In [290]:
print(tensor_1)

tensor([-4.2000, -0.1000,  0.2000,  4.6000])


In [ ]:
"""
torch.trunc(tensor_1)
tensor_1.trunc()
torch.fix(tensor_1)
tensor_1.fix()
"""

In [291]:
torch.trunc(tensor_1)

tensor([-4., -0.,  0.,  4.])

In [292]:
tensor_1.trunc()

tensor([-4., -0.,  0.,  4.])

In [293]:
torch.fix(tensor_1)

tensor([-4., -0.,  0.,  4.])

In [294]:
tensor_1.fix()

tensor([-4., -0.,  0.,  4.])

## sum

### torch.sum
torch.sum(input, *, dtype=None)  
torch.sum(input, dim, keepdim=False, *, dtype=None)

In [11]:
tensor_1 = torch.arange(1, 2 * 3 * 4 + 1, dtype=torch.float).view(2, 3, 4)
print(tensor_1)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])


In [12]:
torch.sum(tensor_1)

tensor(300.)

In [13]:
tensor_1.sum()

tensor(300.)

In [14]:
torch.sum(tensor_1, (1, 2)) # 对dim=1和dim=2求和

tensor([ 78., 222.])

In [15]:
print((1 + 12) * 6, ",", (13 + 24) * 6)

78 , 222


In [16]:
torch.sum(tensor_1, (2, 0)) # 对dim=0和dim=2求和

tensor([ 68., 100., 132.])

In [17]:
print((1 + 2 + 3 + 4) + (13 + 14 + 15 + 16), ",",
      (5 + 6 + 7 + 8) + (17 + 18 + 19 + 20), ",",
      (9 + 10 + 11 + 12) + (21 + 22 + 23 + 24))

68 , 100 , 132


In [18]:
torch.sum(tensor_1, (1, 2), keepdim=True)

tensor([[[ 78.]],

        [[222.]]])

### torch.nansum
torch.nansum(input, *, dtype=None)  
torch.nansum(input, dim, keepdim=False, *, dtype=None)

In [19]:
tensor_2 = torch.tensor([[1., 2., float('nan'), 4.], [5., float('nan'), 7., 8.]])

In [20]:
torch.nansum(tensor_2)

tensor(27.)

In [21]:
tensor_2.nansum()

tensor(27.)

In [22]:
torch.nansum(tensor_2, dim=(0, 1))

tensor(27.)

In [23]:
torch.sum(tensor_2)

tensor(nan)

In [24]:
torch.nansum(tensor_2, dim=0)

tensor([ 6.,  2.,  7., 12.])

In [25]:
torch.nansum(tensor_2, dim=1)

tensor([ 7., 20.])

### torch.cumsum
torch.cumsum(input, dim, *, dtype=None, out=None)
$$y_i = x_1 + x_2 + x_3 + \cdots + x_i $$

In [26]:
print(tensor_1)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])


In [27]:
torch.cumsum(tensor_1, dim=0)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[14., 16., 18., 20.],
         [22., 24., 26., 28.],
         [30., 32., 34., 36.]]])

In [28]:
torch.cumsum(tensor_1, dim=2)

tensor([[[ 1.,  3.,  6., 10.],
         [ 5., 11., 18., 26.],
         [ 9., 19., 30., 42.]],

        [[13., 27., 42., 58.],
         [17., 35., 54., 74.],
         [21., 43., 66., 90.]]])

### torch.logsumexp
torch.logsumexp(input, dim, keepdim=False, *, out=None)
$$logcumsumexp(x)_i = log\sum_j \exp(x_{ij}) $$ 

In [29]:
torch.logsumexp(tensor_1/100, dim=2)

tensor([[1.4114, 1.4514, 1.4914],
        [1.5314, 1.5714, 1.6114]])

In [30]:
import math
print("上式的[0, 0]元素 =", math.log(math.exp(0.0100) + math.exp(0.0200) + math.exp(0.0300) + math.exp(0.0400)))

上式的[0, 0]元素 = 1.4113568602344964


### torch.logcumsumexp
torch.logcumsumexp(input, dim, *, out=None)
$$logcumsumexp(x)_{ij} = log\sum_{j=0}^i \exp(x_{ij}) $$ 

In [31]:
torch.logcumsumexp(tensor_1/100, dim=2)

tensor([[[0.0100, 0.7082, 1.1186, 1.4114],
         [0.0500, 0.7482, 1.1586, 1.4514],
         [0.0900, 0.7882, 1.1986, 1.4914]],

        [[0.1300, 0.8282, 1.2386, 1.5314],
         [0.1700, 0.8682, 1.2786, 1.5714],
         [0.2100, 0.9082, 1.3186, 1.6114]]])

In [32]:
print("上式的[0, 0, 2]元素 =", math.log(math.exp(0.0100) + math.exp(0.0200)))
print("上式的[0, 0, 3]元素 =", math.log(math.exp(0.0100) + math.exp(0.0200) + math.exp(0.0300)))

上式的[0, 0, 2]元素 = 0.7081596805078623
上式的[0, 0, 3]元素 = 1.118645621723669


### torch.trace(input) 迹
**迹**: 二维矩阵对角线上元素的总和

In [33]:
torch.arange(1., 10.).view(3, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [34]:
torch.trace(torch.arange(1., 10.).view(3, 3))

tensor(15.)

In [35]:
1 + 5 + 9

15

## mean

### torch.mean
torch.mean(input, *, dtype=None)  
torch.mean(input, dim, keepdim=False, *, dtype=None, out=None)

In [36]:
print(tensor_1)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])


In [37]:
torch.mean(tensor_1)

tensor(12.5000)

In [38]:
tensor_1.mean()

tensor(12.5000)

In [39]:
torch.mean(tensor_1, (1, 2)) # 对dim=1和dim=2求平均

tensor([ 6.5000, 18.5000])

In [40]:
print((1 + 12) * 6 / 12, ",", (13 + 24) * 6 / 12)

6.5 , 18.5


In [41]:
torch.mean(tensor_1, (2, 0)) # 对dim=0和dim=2求和

tensor([ 8.5000, 12.5000, 16.5000])

In [42]:
print(((1 + 2 + 3 + 4) + (13 + 14 + 15 + 16)) / 8, ",",
      ((5 + 6 + 7 + 8) + (17 + 18 + 19 + 20)) / 8, ",",
      ((9 + 10 + 11 + 12) + (21 + 22 + 23 + 24)) / 8)

8.5 , 12.5 , 16.5


### torch.nanmean
torch.nanmean(input, dim=None, keepdim=False, *, dtype=None, out=None)

In [43]:
print(tensor_2)

tensor([[1., 2., nan, 4.],
        [5., nan, 7., 8.]])


In [44]:
torch.nanmean(tensor_2)

tensor(4.5000)

In [45]:
tensor_2.nanmean()

tensor(4.5000)

In [46]:
torch.nanmean(tensor_2, dim=(0, 1))

tensor(4.5000)

In [47]:
(1 + 2 + 4 + 5 + 7 + 8) / 6

4.5

In [48]:
torch.mean(tensor_2)

tensor(nan)

In [49]:
torch.nanmean(tensor_2, dim=0)

tensor([3., 2., 7., 6.])

In [50]:
torch.nanmean(tensor_2, dim=1)

tensor([2.3333, 6.6667])

### torch.var_mean 方差和均值
torch.var_mean(input, dim=None, \*, correction=1, keepdim=False, out=None)
$$\sigma^2 = \frac{1}{N-\delta N}\sum_{i=1}^{N-1} (x_i-\bar{x})^2$$
where $x_i$ is the sample set of elements, $\bar{x}$ is the sample mean, $N$ is the number of samples, $\delta N$ is the correction.

Returns: A tuple (var, mean) containing the variance and mean.

In [51]:
print(tensor_1)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])


In [52]:
variance, mean = torch.var_mean(tensor_1, dim=2, correction=1)

In [53]:
variance

tensor([[1.6667, 1.6667, 1.6667],
        [1.6667, 1.6667, 1.6667]])

In [54]:
count = 0
for ii in range(1, 5):
    count += (ii - 2.5)**2
print("上式的[0, 0]元素 =", count / (4 - 1))

上式的[0, 0]元素 = 1.6666666666666667


In [55]:
mean

tensor([[ 2.5000,  6.5000, 10.5000],
        [14.5000, 18.5000, 22.5000]])

In [56]:
torch.mean(tensor_1, dim=2)

tensor([[ 2.5000,  6.5000, 10.5000],
        [14.5000, 18.5000, 22.5000]])

In [57]:
torch.var_mean(tensor_1, dim=(1, 2), correction=1)

(tensor([13., 13.]), tensor([ 6.5000, 18.5000]))

In [58]:
count = 0
for ii in range(1, 13):
    count += (ii - 6.5)**2
print("方差的第一元素 =", count / (12 - 1))

方差的第一元素 = 13.0


### torch.std_mean 标准差和均值
torch.std_mean(input, dim=None, *, correction=1, keepdim=False, out=None)
$$\sigma = \sqrt{\frac{1}{N-\delta N}\sum_{i=1}^{N-1} (x_i-\bar{x})^2}$$
where $x_i$ is the sample set of elements, $\bar{x}$ is the sample mean, $N$ is the number of samples, $\delta N$ is the correction.

Returns: A tuple (std, mean) containing the standard deviation and mean.

In [59]:
std, mean = torch.std_mean(tensor_1, dim=2, correction=1)

In [60]:
std

tensor([[1.2910, 1.2910, 1.2910],
        [1.2910, 1.2910, 1.2910]])

In [61]:
count = 0
for ii in range(1, 5):
    count += (ii - 2.5)**2
print("上式的[0, 0]元素 =", (count / (4 - 1))**0.5)

上式的[0, 0]元素 = 1.2909944487358056


In [62]:
mean

tensor([[ 2.5000,  6.5000, 10.5000],
        [14.5000, 18.5000, 22.5000]])

In [63]:
torch.mean(tensor_1, dim=2)

tensor([[ 2.5000,  6.5000, 10.5000],
        [14.5000, 18.5000, 22.5000]])

In [64]:
torch.std_mean(tensor_1, dim=(1, 2), correction=1)

(tensor([3.6056, 3.6056]), tensor([ 6.5000, 18.5000]))

In [65]:
count = 0
for ii in range(1, 13):
    count += (ii - 6.5)**2
print("方差的第一元素 =", (count / (12 - 1))**0.5)

方差的第一元素 = 3.605551275463989


## max/min

### torch.max
- [torch.max(input)](https://pytorch.org/docs/stable/generated/torch.max.html)<br>
returns the maximum value 
- [torch.max(input, dim, keepdim=False, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.max.html)<br>
returns tuple of two output tensors (max, max_indices)

In [66]:
print(tensor_1)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])


In [67]:
torch.max(tensor_1)

tensor(24.)

In [68]:
torch.max(tensor_1, dim=2)

torch.return_types.max(
values=tensor([[ 4.,  8., 12.],
        [16., 20., 24.]]),
indices=tensor([[3, 3, 3],
        [3, 3, 3]]))

### torch.amax
[torch.amax(input, dim, keepdim=False, *, out=None)](https://pytorch.org/docs/stable/generated/torch.amax.html)

In [69]:
torch.amax(tensor_1)

tensor(24.)

In [70]:
torch.amax(tensor_1, dim=2)

tensor([[ 4.,  8., 12.],
        [16., 20., 24.]])

In [71]:
torch.amax(tensor_1, dim=(1, 2))

tensor([12., 24.])

### torch.min
- [torch.min(input)](https://pytorch.org/docs/stable/generated/torch.min.html)<br>
returns the minimum value 
- [torch.min(input, dim, keepdim=False, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.min.html)<br>
returns tuple of two output tensors (min, min_indices)

In [72]:
torch.min(tensor_1)

tensor(1.)

In [73]:
torch.min(tensor_1, dim=2)

torch.return_types.min(
values=tensor([[ 1.,  5.,  9.],
        [13., 17., 21.]]),
indices=tensor([[0, 0, 0],
        [0, 0, 0]]))

### torch.amin
[torch.amin(input, dim, keepdim=False, *, out=None)](https://pytorch.org/docs/stable/generated/torch.amin.html)

In [74]:
torch.amin(tensor_1)

tensor(1.)

In [75]:
torch.amin(tensor_1, dim=2)

tensor([[ 1.,  5.,  9.],
        [13., 17., 21.]])

In [76]:
torch.amin(tensor_1, dim=(1, 2))

tensor([ 1., 13.])

### torch.aminmax
[torch.aminmax(input, *, dim=None, keepdim=False, out=None)](https://pytorch.org/docs/stable/generated/torch.aminmax.html)

returns minimum and maximum values

In [77]:
torch.aminmax(tensor_1)

torch.return_types.aminmax(
min=tensor(1.),
max=tensor(24.))

In [78]:
torch.aminmax(tensor_1, dim=2)

torch.return_types.aminmax(
min=tensor([[ 1.,  5.,  9.],
        [13., 17., 21.]]),
max=tensor([[ 4.,  8., 12.],
        [16., 20., 24.]]))

### torch.argmax 最大值的索引
[torch.argmax(input, dim, keepdim=False)](https://pytorch.org/docs/stable/generated/torch.argmax.html)

In [79]:
torch.argmax(tensor_1)

tensor(23)

In [80]:
torch.argmax(tensor_1, dim=2)

tensor([[3, 3, 3],
        [3, 3, 3]])

### torch.argmin 最小值的索引
[torch.argmin(input, dim=None, keepdim=False)](https://pytorch.org/docs/stable/generated/torch.argmin.html)

In [81]:
torch.argmin(tensor_1)

tensor(0)

In [82]:
torch.argmin(tensor_1, dim=2)

tensor([[0, 0, 0],
        [0, 0, 0]])

### 取大/取小
1. [torch.maximum(input, other, *, out=None)](https://pytorch.org/docs/stable/generated/torch.maximum.html) $\iff$ [torch.max(input, other, *, out=None)](https://pytorch.org/docs/stable/generated/torch.max.html)
2. [torch.minimum(input, other, *, out=None)](https://pytorch.org/docs/stable/generated/torch.minimum.html) $\iff$ [torch.min(input, other, *, out=None)](https://pytorch.org/docs/stable/generated/torch.min.html)
3. [torch.fmax(input, other, *, out=None)](https://pytorch.org/docs/stable/generated/torch.fmax.html)
4. [torch.fmin(input, other, *, out=None)](https://pytorch.org/docs/stable/generated/torch.fmin.html)

In [83]:
torch.maximum(torch.tensor((1, 2, -1)),
              torch.tensor((3, 0, 4)))

tensor([3, 2, 4])

In [84]:
torch.max(torch.tensor((1, 2, -1)),
          torch.tensor((3, 0, 4)))

tensor([3, 2, 4])

In [85]:
torch.minimum(torch.tensor((1, 2, -1)),
              torch.tensor((3, 0, 4)))

tensor([ 1,  0, -1])

In [86]:
torch.min(torch.tensor((1, 2, -1)),
          torch.tensor((3, 0, 4)))

tensor([ 1,  0, -1])

In [87]:
torch.fmax(torch.tensor([9.7, float('nan'), 3.1, float('nan')]),
           torch.tensor([-2.2, 0.5, float('nan'), float('nan')]))

tensor([9.7000, 0.5000, 3.1000,    nan])

In [88]:
torch.fmin(torch.tensor([9.7, float('nan'), 3.1, float('nan')]),
           torch.tensor([-2.2, 0.5, float('nan'), float('nan')]))

tensor([-2.2000,  0.5000,  3.1000,     nan])

### torch.cummax
[torch.cummax(input, dim, *, out=None)](https://pytorch.org/docs/stable/generated/torch.cummax.html)
$$y_i=max(x_1, x_2, x_3, \dots, x_i)$$ 

In [89]:
print(tensor_1)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])


In [93]:
torch.cummax(tensor_1, dim=2)

torch.return_types.cummax(
values=tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]]),
indices=tensor([[[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]],

        [[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]]]))

### torch.cummin
[torch.cummin(input, dim, *, out=None)](https://pytorch.org/docs/stable/generated/torch.cummin.html)
$$y_i=min(x_1, x_2, x_3, \dots, x_i)$$ 

In [95]:
torch.cummin(tensor_1, dim=2)

torch.return_types.cummin(
values=tensor([[[ 1.,  1.,  1.,  1.],
         [ 5.,  5.,  5.,  5.],
         [ 9.,  9.,  9.,  9.]],

        [[13., 13., 13., 13.],
         [17., 17., 17., 17.],
         [21., 21., 21., 21.]]]),
indices=tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]))

## 角度(degree)与弧度(radian)

### torch.deg2rad
[torch.deg2rad(input, *, out=None)](https://pytorch.org/docs/stable/generated/torch.deg2rad.html) 角度$\to$弧度
### torch.rad2deg
[torch.rad2deg(input, *, out=None)](https://pytorch.org/docs/stable/generated/torch.rad2deg.html#torch.rad2deg) 弧度$\to$角度

In [66]:
torch.pi

3.141592653589793

In [67]:
degrees = torch.tensor([0., 30., 45., 60., 90.])

In [68]:
torch.deg2rad(degrees)

tensor([0.0000, 0.5236, 0.7854, 1.0472, 1.5708])

In [69]:
radians = torch.tensor([0., torch.pi/6., torch.pi/4., torch.pi/3., torch.pi/2.])
print(radians)

tensor([0.0000, 0.5236, 0.7854, 1.0472, 1.5708])


In [70]:
radians / torch.pi * 180

tensor([ 0., 30., 45., 60., 90.])

In [71]:
torch.rad2deg(torch.tensor([0., torch.pi/6., torch.pi/4., torch.pi/3., torch.pi/2.]))

tensor([ 0.0000, 30.0000, 45.0000, 60.0000, 90.0000])

## 初等函数

命令 | 用法 | 公式
:- | :- | :-:
torch.sin | [torch.sin(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.sin.html) |  $$out_i = \sin(input_i)$$
torch.asin | [torch.asin(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.asin.html)<br>$\iff$ [torch.arcsin(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.arcsin.html) | $$out_i = \sin^{-1}(input_i)$$
torch.cos | [torch.cos(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.cos.html) |  $$out_i = \cos(input_i)$$
torch.acos | [torch.acos(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.acos.html)<br>$\iff$ [torch.arccos(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.arccos.html) | $$out_i = \cos^{-1}(input_i)$$
torch.tan | [torch.tan(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.tan.html) |  $$out_i = \tan(input_i)$$
torch.atan<span id='id_atan'></span> | [torch.atan(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.atan.html)<br>$\iff$ [torch.arctan(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.arctan.html) | $$out_i = \tan^{-1}(input_i), input_i = \frac{y_i}{x_i} = \frac{\sin(out_i)}{\cos(out_i)}$$
torch.atan2<span id='id_atan2'></span> | [torch.atan2(input, other, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.atan2.html)<br>$\iff$[torch.arctan2(input, other, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.arctan2.html) | $$out_i = \tan^{-1}(\frac{input_i}{other_i})$$ $$input_i = y_i = \sin(out_i), other_i = x_i = \cos(out_i)$$
torch.angle<span id='id_angle'></span> | [torch.angle(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.angle.html) | $$ out_i = angle(input_i) \iff out_i = tan^{-1}\frac{y_i}{x_i}, input_i = x_i + y_i*j$$ $$x_i = \cos(out_i), y_i = \sin(out_i)$$
---- | ---- | ---- 
torch.sinh | [torch.sinh(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.sinh.html) |  $$out_i = \sinh(input_i)$$
torch.asinh | [torch.asinh(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.asinh.html)<br>$\iff$ [torch.arcsinh(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.arcsinh.html) | $$out_i = \sinh^{-1}(input_i)$$
torch.cosh | [torch.cosh(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.cosh.html) |  $$out_i = \cosh(input_i)$$
torch.acosh | [torch.acosh(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.acosh.html)<br>$\iff$ [torch.arccosh(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.arccosh.html) | $$out_i = \cosh^{-1}(input_i)$$
torch.tanh | [torch.tanh(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.tanh.html) |  $$out_i = \tanh(input_i)$$
torch.atanh | [torch.atanh(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.atanh.html)<br>$\iff$ [torch.arctanh(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.arctanh.html) | $$out_i = \tanh^{-1}(input_i)$$
---- | ---- | ---- 
torch.sqrt | [torch.sqrt(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.sqrt.html) | $$out_i = \sqrt{input_i} = {input_i}^{\frac{1}{2}}$$
torch.rsqrt | [torch.rsqrt(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.rsqrt.html) | $$out_i = \frac{1}{\sqrt{input_i}} = {input_i}^{-\frac{1}{2}}$$
torch.square | [torch.square(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.square.html) | $$out_i = input_i^2$$
torch.pow<span id='id_pow'></span> | [torch.pow(input, exponent, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.pow.html) | $$out_i = {input_i}^{exponent},\ \ i.e., y = x^a$$
torch.float_power<span id='id_float_power'></span> | [torch.float_power(input, exponent, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.float_power.html) | 如果两个输入都不是复数, 则返回torch.foat64张量;<br>如果一个或多个输入是复数, 则会返回torch.complex128张量
---- | ---- | ---- 
torch.exp | [torch.exp(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.exp.html) | $$out_i = e^{input_i}$$
torch.exp2 | [torch.exp2(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.exp2.html)<br>$\iff$ [torch.special.exp2(input, \*, out=None)](https://pytorch.org/docs/stable/special.html#torch.special.exp2) | $$out_i = 2^{input_i}$$
torch.ldexp | [torch.ldexp(input, other, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.ldexp.html) | $$out_i = input_i * 2^{other_i}$$
torch.frexp<span id='id_frexp'></span> | [torch.frexp(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.frexp.html) | 将输入分解为mantissa和exponent张量, 即 $$input_i=mantissa_i * 2^{exponent_i}$$
torch.logaddexp | [torch.logaddexp(input, other, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.logaddexp.html) | $$out_i = \log_e(e^{input_i} + e^{other_i})$$
torch.logaddexp2 | [torch.logaddexp2(input, other, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.logaddexp2.html) | $$out_i = \log_2(2^{input_i} + 2^{other_i})$$
torch.expm1 | [torch.expm1(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.expm1.html)<br>$\iff$ [torch.special.expm1(input, \*, out=None)](https://pytorch.org/docs/stable/special.html#torch.special.expm1) | $$out_i = e^{input_i} - 1$$
torch.sigmoid | [torch.sigmoid(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.sigmoid.html)<br>$\iff$ [torch.special.expit(input, \*, out=None)](https://pytorch.org/docs/stable/special.html#torch.special.expit) | $$out_i = \frac{1}{1+e^{-input_i}}$$
---- | ---- | ---- 
torch.log | [torch.log(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.log.html) | $$out_i = \log_e(input_i)$$
torch.log2 | [torch.log2(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.log2.html) | $$out_i = \log_2(input_i)$$
torch.log10 | [torch.log10(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.log10.html) | $$out_i = \log_{10}(input_i)$$
torch.log1p | [torch.log1p(input, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.log1p.html) | $$out_i = \log_e(input_i+1)$$
torch.logit | [torch.logit(input, eps=None, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.logit.html)<br>$\iff$ [torch.special.logit(input, eps=None, \*, out=None)](https://pytorch.org/docs/stable/special.html#torch.special.logit) | $$out_i = \log_e(\frac{z_i}{1-z_i})$$, $$z_i = \begin{cases} \begin{array}{l,l}
input_i, & if\ \ eps=NaN \\
eps, & if\ \ input_i<eps \\
input_i, & if\ \ eps\leq input_i\leq 1-eps \\
1-eps, & if\ \ input_i>1-eps \\
\end{array} \end{cases}$$
torch.xlogy | [torch.xlogy(input, other, \*, out=None)](https://pytorch.org/docs/stable/generated/torch.xlogy.html)<br>$\iff$ [torch.special.xlogy(input, other, \*, out=None)](https://pytorch.org/docs/stable/special.html#torch.special.xlogy) | $$out_i = \begin{cases} \begin{array}{l,l}
NaN, & if\ \ other_i=NaN \\
0, & if\ \ input_i=0.0 \\
input_i * \log(other_i), & otherwise \\
\end{array} \end{cases}$$
note: | $\log_e(x) = \ln(x)$, $\log_{10}(x) = \lg(x)$

* [torch.atan](#id_atan) vs [torch.atan2](#id_atan2) vs [torch.angle](#id_angle)

In [80]:
print("radians =", radians)

radians = tensor([0.0000, 0.5236, 0.7854, 1.0472, 1.5708])


In [90]:
x = torch.cos(radians)

In [91]:
y = torch.sin(radians)

In [92]:
torch.atan(torch.abs(y/x)) / torch.pi * 180

tensor([ 0.0000, 30.0000, 45.0000, 60.0000, 90.0000])

In [93]:
torch.atan2(y, x) / torch.pi * 180

tensor([ 0., 30., 45., 60., 90.])

In [95]:
torch.angle(torch.complex(x, y)) / torch.pi * 180

tensor([ 0., 30., 45., 60., 90.])

* [torch.pow](#id_pow) vs [torch.float_power](#id_float_power)

In [15]:
tensor_1 = torch.arange(1., 9.)

In [16]:
tensor_1

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [17]:
torch.pow(tensor_1, tensor_1)

tensor([1.0000e+00, 4.0000e+00, 2.7000e+01, 2.5600e+02, 3.1250e+03, 4.6656e+04,
        8.2354e+05, 1.6777e+07])

In [18]:
torch.float_power(tensor_1, tensor_1)

tensor([1.0000e+00, 4.0000e+00, 2.7000e+01, 2.5600e+02, 3.1250e+03, 4.6656e+04,
        8.2354e+05, 1.6777e+07], dtype=torch.float64)

* [torch.frexp](#id_frexp)

In [19]:
torch.frexp(tensor_1)

torch.return_types.frexp(
mantissa=tensor([0.5000, 0.5000, 0.7500, 0.5000, 0.6250, 0.7500, 0.8750, 0.5000]),
exponent=tensor([1, 2, 2, 3, 3, 3, 3, 4], dtype=torch.int32))

## 阶跃函数

### torch.heaviside
torch.heaviside(input, values, *, out=None)
$$ heaviside(input,values) = \begin{cases} \begin{array}{l,l}
0, & input < 0 \\
values, & input = 0\\
1, & input > 0 \\
\end{array} \end{cases} $$

In [329]:
torch.heaviside(input=torch.tensor([-1.5, 0, 2.0]), values=torch.tensor([3.]))

tensor([0., 3., 1.])

In [330]:
torch.heaviside(input=torch.tensor([-1.5, 0, 2.0]), values=torch.tensor([1.2, -2.0, 3.5]))

tensor([ 0., -2.,  1.])

### torch.clamp
torch.clamp(input, min=None, max=None, *, out=None)  
$\iff$ torch.clip(input, min=None, max=None, *, out=None)  
$$ out_i = \begin{cases} \begin{array}{l,l}
min_i, & input_i <= min_i \\
input_i, &  min_i < input_i < max_i \\
max_i, & input_i >= max_i \\
\end{array} \end{cases} $$

In [332]:
torch.clamp(input=torch.tensor([-1.5, 0, 2.0]), min=-0.5, max=0.5)

tensor([-0.5000,  0.0000,  0.5000])

In [347]:
torch.clamp(input=torch.tensor([-1.5, 0, 2.0]), min=torch.tensor([-0.5, -1.0, 0.0]), max=torch.tensor([0.5, 1.0, 1.0]))

tensor([-0.5000,  0.0000,  1.0000])

### torch.sign
torch.sign(input, *, out=None)
$$ out_i = \begin{cases} \begin{array}{l,l}
-1, & input_i < 0 \\
0, & input_i = 0\\
1, & input_i > 0 \\
\end{array} \end{cases} $$

In [348]:
torch.sign(input=torch.tensor([-1.5, -0.0, 0.0, 2.0]))

tensor([-1.,  0.,  0.,  1.])

### torch.signbit
torch.signbit(input, *, out=None)
$$ out_i = \begin{cases} \begin{array}{l,l}
True, & input_i < 0 \\
False, & input_i >= 0 \\
\end{array} \end{cases} $$

In [340]:
torch.signbit(input=torch.tensor([-1.5, -0.0, 0.0, 2.0]))

tensor([ True, False, False, False])

### torch.copysign
torch.copysign(input, other, *, out=None)
$$ out_i = \begin{cases} \begin{array}{l,l}
-\left| input_i \right|, & other_i<= -0.0 \\
\left| input_i \right|, & other_i >= 0.0\\
\end{array} \end{cases} $$

In [349]:
torch.copysign(input=torch.tensor([-1.5, 1.5]), other=1.0)

tensor([1.5000, 1.5000])

In [345]:
torch.copysign(input=torch.tensor([-1.5, -1.5, -1.5, -1.5]),
               other=torch.tensor([-1.5, -0.0, 0.0, 2.0]))

tensor([-1.5000, -1.5000,  1.5000,  1.5000])

In [346]:
torch.copysign(input=torch.tensor([2.0, 2.0, 2.0, 2.0]),
               other=torch.tensor([-1.5, -0.0, 0.0, 2.0]))

tensor([-2., -2.,  2.,  2.])

## todo: 复数
- https://pytorch.org/docs/stable/generated/torch.sgn.html
- https://pytorch.org/docs/stable/generated/torch.view_as_complex.html
- https://pytorch.org/docs/stable/generated/torch.is_complex.html
- https://pytorch.org/docs/stable/generated/torch.complex.html
- https://pytorch.org/docs/stable/generated/torch.polar.html
- 
- https://pytorch.org/docs/stable/generated/torch.is_conj.html
- https://pytorch.org/docs/stable/generated/torch.conj.html
- https://pytorch.org/docs/stable/generated/torch.adjoint.html
- https://pytorch.org/docs/stable/generated/torch.conj_physical.html
- https://pytorch.org/docs/stable/generated/torch.resolve_conj.html
- 
- https://pytorch.org/docs/stable/generated/torch.rot90.html
-
- https://pytorch.org/docs/stable/torch.html

In [ ]:
"""
torch.complex(real, imag, *, out=None)  'out = real + imag*j'
"""
real = torch.tensor([1, 2], dtype=torch.float32)
imag = torch.tensor([3, 4], dtype=torch.float32)
print( torch.complex(real, imag) )
"""
torch.polar(abs, angle, *, out=None)  'out = abs*cos(angle)+abs*sin(angle)*j
"""
abs = torch.tensor([1, 2], dtype=torch.float64)
angle = torch.tensor([3.1415926/2, 5*3.1415926/4], dtype=torch.float64)
print( torch.polar(abs, angle) ) 
"""
torch.conj(input, *, out=None)
共轭复数，两个实部相等，虚部互为相反数
"""
torch.conj(torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j]))

## todo: 位运算

In [ ]:
"""
torch.bitwise_and(input, other, *, out=None)
按位与
"""
print( torch.bitwise_and(torch.tensor([-1, -2, 3]), torch.tensor([1, 0, 3])) )
print( torch.bitwise_and(torch.tensor([True, True, False]), torch.tensor([False, True, False])) )
"""
torch.bitwise_or(input, other, *, out=None)
按位或
"""
print( torch.bitwise_or(torch.tensor([-1, -2, 3]), torch.tensor([1, 0, 3])) )
print( torch.bitwise_or(torch.tensor([True, True, False]), torch.tensor([False, True, False])) )
"""
torch.bitwise_xor(input, other, *, out=None)
按位异或
"""
print( torch.bitwise_xor(torch.tensor([-1, -2, 3]), torch.tensor([1, 0, 3])) )
print( torch.bitwise_xor(torch.tensor([True, True, False]), torch.tensor([False, True, False])) )
"""
torch.bitwise_not(input, *, out=None)
按位取反，即 ~x = -（x+1）
"""
print( torch.bitwise_not(torch.tensor([-1, -2, 3])) )


todo:
https://pytorch.org/docs/stable/generated/torch.logical_and.html#torch.logical_and
https://pytorch.org/docs/stable/generated/torch.logical_or.html#torch.logical_or
https://pytorch.org/docs/stable/generated/torch.logical_not.html#torch.logical_not
https://pytorch.org/docs/stable/generated/torch.logical_xor.html#torch.logical_xor