In [2]:
import torch
import numpy

# list, numpy, tensor相互转化
[![](https://mermaid.ink/img/pako:eNp1ks1qwzAMx18l6ORAlwfIYdCP607raRiCSJwlENvBcRil7bG77AV22ROMHQqDwp5nKXuMKXFImbfpJEs_SX8hbyHVmYAY8ko_pAUaG6xXXAVkc2aFarQJgyuy6x0HTFwkUq2sNyzsDsfPj9fu8dC9PXPYBQs2JEJXv5jqrDZpEWEzljM05mctVw7JjZaJa_4vs770OJ-O56fT1_vLlLR_JUnZ3JdERGR1VTaWhT2wZL0_Kl9O2KAlIhhJUeKQflGf-7XhyPqivbBHO6FcwQykMBLLjA6z7WfRhEJIwSEmNxM5tpXlwNWeUGytvt2oFGJrWjGDts7QilWJ9wYlxDlWDUVrVHdaX94iK0nDjTv-8Af23xzAxMU?type=png)](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNp1ks1qwzAMx18l6ORAlwfIYdCP607raRiCSJwlENvBcRil7bG77AV22ROMHQqDwp5nKXuMKXFImbfpJEs_SX8hbyHVmYAY8ko_pAUaG6xXXAVkc2aFarQJgyuy6x0HTFwkUq2sNyzsDsfPj9fu8dC9PXPYBQs2JEJXv5jqrDZpEWEzljM05mctVw7JjZaJa_4vs770OJ-O56fT1_vLlLR_JUnZ3JdERGR1VTaWhT2wZL0_Kl9O2KAlIhhJUeKQflGf-7XhyPqivbBHO6FcwQykMBLLjA6z7WfRhEJIwSEmNxM5tpXlwNWeUGytvt2oFGJrWjGDts7QilWJ9wYlxDlWDUVrVHdaX94iK0nDjTv-8Af23xzAxMU)

In [ ]:
"""
                             tensor
                         ↗          ↘↖
torch.as_tensor(list1) ↗              ↘↖torch.as_tensor(arr1)
torch.Tensor(list1)  ↗                  ↘↖torch.from_numpy(arr1)
torch.tensor(list1)↗       tensor1.numpy()↘↖torch.Tensor(arr1) 
                 ↗                          ↘↖torch.tensor(arr1)
               ↗       array1.tolist()        ↘↖
            list      <-----------------        numpy
                      ----------------->
                      numpy.array(list1)
"""

## numpy <-> tensor
> Tensors on the CPU and NumPy arrays can share their underlying memory location, and **changing one will change the other**

In [12]:
arr1 = numpy.array([1,1,1])

arr2tensor_1 = torch.from_numpy(arr1)    # 共享内存
arr2tensor_2 = torch.as_tensor(arr1)     # 共享内存
arr2tensor_3 = torch.tensor(arr1)        # 深拷贝
arr2tensor_4 = torch.Tensor(arr1)        # 深拷贝
tensor2arr_1 = arr2tensor_1.numpy()      # 共享内存

print('Before modify:', arr2tensor_1)
print('Before modify:', arr2tensor_2)
print('Before modify:', arr2tensor_3)
print('Before modify:', arr2tensor_4)
print('Before modify:', tensor2arr_1)

arr1 += 1
print('After modify:', arr2tensor_1)
print('After modify:', arr2tensor_2)
print('After modify:', arr2tensor_3)
print('After modify:', arr2tensor_4)
print('After modify:', tensor2arr_1)

Before modify: tensor([1, 1, 1])
Before modify: tensor([1, 1, 1])
Before modify: tensor([1, 1, 1])
Before modify: tensor([1., 1., 1.])
Before modify: [1 1 1]
After modify: tensor([2, 2, 2])
After modify: tensor([2, 2, 2])
After modify: tensor([1, 1, 1])
After modify: tensor([1., 1., 1.])
After modify: [2 2 2]


## list -> tensor

In [11]:
list_1 = [1,1,1]

list2tensor_1 = torch.as_tensor(list_1)   # 深拷贝, 保留原数据类型
list2tensor_2 = torch.tensor(list_1)      # 深拷贝, 保留原数据类型
list2tensor_3 = torch.Tensor(list_1)      # 深拷贝, 保存为float

print('Before modify:', list2tensor_1, list2tensor_1.dtype)
print('Before modify:', list2tensor_2, list2tensor_2.dtype)
print('Before modify:', list2tensor_3, list2tensor_3.dtype)

list_1[1] = 2
print('After modify:', list2tensor_1, list2tensor_1.dtype)
print('After modify:', list2tensor_2, list2tensor_2.dtype)
print('After modify:', list2tensor_3, list2tensor_3.dtype)

Before modify: tensor([1, 1, 1]) torch.int64
Before modify: tensor([1, 1, 1]) torch.int64
Before modify: tensor([1., 1., 1.]) torch.float32
After modify: tensor([1, 1, 1]) torch.int64
After modify: tensor([1, 1, 1]) torch.int64
After modify: tensor([1., 1., 1.]) torch.float32


## torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False)
Data type                | dtype                         | Legacy Constructors
:- | :- | :-
32-bit floating point    | torch.float32 or torch.float  | torch.*.FloatTensor
64-bit floating point    | torch.float64 or torch.double | torch.*.DoubleTensor
64-bit complex           | torch.complex64 or torch.cfloat
128-bit complex          | torch.complex128 or torch.cdouble
16-bit floating point 1  | torch.float16 or torch.half   | torch.*.HalfTensor
16-bit floating point 2  | torch.bfloat16                | torch.*.BFloat16Tensor
8-bit integer (unsigned) | torch.uint8                   | torch.*.ByteTensor
8-bit integer (signed)   | torch.int8                    | torch.*.CharTensor
16-bit integer (signed)  | torch.int16 or torch.short    | torch.*.ShortTensor
32-bit integer (signed)  | torch.int32 or torch.int      | torch.*.IntTensor
64-bit integer (signed)  | torch.int64 or torch.long     | torch.*.LongTensor
Boolean                  | torch.bool                    | torch.*.BoolTensor

In [15]:
tensor1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float)
print(tensor1)
print( type(tensor1) )
print('is a tensor?', torch.is_tensor(tensor1) )
print( tensor1.dtype )
print( tensor1.device )

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
<class 'torch.Tensor'>
is a tensor? True
torch.float32
cpu


In [14]:
print(torch.tensor([1], dtype = torch.complex64), 'is complex?', torch.is_complex(torch.tensor([1], dtype = torch.complex64)))
print(torch.tensor([1], dtype = torch.complex128), 'is complex?', torch.is_complex(torch.tensor([1], dtype = torch.complex128)))
print(torch.tensor([1], dtype = torch.float32), 'is float?', torch.is_floating_point(torch.tensor([1], dtype = torch.float32)))
print(torch.tensor([1], dtype = torch.float64), 'is float?', torch.is_floating_point(torch.tensor([1], dtype = torch.float64)))
print(torch.tensor([1], dtype = torch.float16), 'is float?', torch.is_floating_point(torch.tensor([1], dtype = torch.float16)))
print(torch.tensor([1], dtype = torch.bfloat16), 'is float?', torch.is_floating_point(torch.tensor([1], dtype = torch.bfloat16)))

tensor([1.+0.j]) is complex? True
tensor([1.+0.j], dtype=torch.complex128) is complex? True
tensor([1.]) is float? True
tensor([1.], dtype=torch.float64) is float? True
tensor([1.], dtype=torch.float16) is float? True
tensor([1.], dtype=torch.bfloat16) is float? True


# 生成操作

In [ ]:
tensor_1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float)

In [ ]:
# 1.基本
"""
torch.zeros(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
"""
print( torch.zeros(5, 3) )
print( '<=>', torch.zeros((5,3)) )
"""
torch.zeros_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)
"""
print( torch.zeros_like(tensor1) )
"""
torch.ones(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
"""
print( torch.ones(5, 3) )
"""
torch.ones_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)
"""
print( torch.ones_like(tensor1) )
"""
torch.eye(n, m=None, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
对角线为1
"""
print( torch.eye(5, 3) )
"""
torch.empty(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) 
生成一个空的tensor(每个元素为随机的极其小的正值，从而不影响数值计算）
"""
print( torch.empty(5, 3) )
"""
torch.empty_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)
"""
print( torch.empty_like(tensor1) )
"""
torch.full(size, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
Creates a tensor of size size filled with fill_value
"""
print( torch.full(size=(2, 3), fill_value=3.141592) )
"""
torch.full_like(input, fill_value, *, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format)
Creates a tensor of size size filled with fill_value
"""
print( torch.full_like(tensor1, fill_value=3.141592) )